package vo.bts;

import java.io.Serializable;
import java.math.BigDecimal;

public class Bts_test implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column BTS_TEST.ID
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column BTS_TEST.NAME
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column BTS_TEST.TYPE_BTS
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    private Integer typeBts;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column BTS_TEST.SYMBOL
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    private String symbol;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column BTS_TEST.TYPE_TRANSMISSION
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    private Integer typeTransmission;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column BTS_TEST.PORT_NUMBER
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    private Integer portNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table BTS_TEST
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column BTS_TEST.ID
     *
     * @return the value of BTS_TEST.ID
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column BTS_TEST.ID
     *
     * @param id the value for BTS_TEST.ID
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column BTS_TEST.NAME
     *
     * @return the value of BTS_TEST.NAME
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column BTS_TEST.NAME
     *
     * @param name the value for BTS_TEST.NAME
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column BTS_TEST.TYPE_BTS
     *
     * @return the value of BTS_TEST.TYPE_BTS
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public Integer getTypeBts() {
        return typeBts;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column BTS_TEST.TYPE_BTS
     *
     * @param typeBts the value for BTS_TEST.TYPE_BTS
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public void setTypeBts(Integer typeBts) {
        this.typeBts = typeBts;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column BTS_TEST.SYMBOL
     *
     * @return the value of BTS_TEST.SYMBOL
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column BTS_TEST.SYMBOL
     *
     * @param symbol the value for BTS_TEST.SYMBOL
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column BTS_TEST.TYPE_TRANSMISSION
     *
     * @return the value of BTS_TEST.TYPE_TRANSMISSION
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public Integer getTypeTransmission() {
        return typeTransmission;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column BTS_TEST.TYPE_TRANSMISSION
     *
     * @param typeTransmission the value for BTS_TEST.TYPE_TRANSMISSION
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public void setTypeTransmission(Integer typeTransmission) {
        this.typeTransmission = typeTransmission;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column BTS_TEST.PORT_NUMBER
     *
     * @return the value of BTS_TEST.PORT_NUMBER
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public Integer getPortNumber() {
        return portNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column BTS_TEST.PORT_NUMBER
     *
     * @param portNumber the value for BTS_TEST.PORT_NUMBER
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    public void setPortNumber(Integer portNumber) {
        this.portNumber = portNumber;
    }

	@Override
	public String toString() {
		return "Bts_test [id=" + id + ", name=" + name + ", typeBts=" + typeBts + ", symbol=" + symbol
				+ ", typeTransmission=" + typeTransmission + ", portNumber=" + portNumber + "]";
	}
}