package vo.bts;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class NocDanhGiaCSHT implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.ID
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.ID_CA_TRUC
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private Integer idCaTruc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.MA_PHONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String maPhong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.TO_UCTT
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String toUctt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.HE_THONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String heThong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.SO_LUONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String soLuong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.DANH_GIA_TAI
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String danhGiaTai;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.HT_TAI_CAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String htTaiCao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.HOAT_DONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String hoatDong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.DE_XUAT
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String deXuat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.GHI_CHU
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String ghiChu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.NGUOI_TAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String nguoiTao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.NGAY_TAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private Date ngayTao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.NGUOI_SUA
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String nguoiSua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.NGAY_SUA
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private Date ngaySua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.GUI_CNOC
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String guiCnoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_DANH_GIA_CSHT.KEY_SHARING
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    private String keySharing;

    
    
    private String nhanCaTruc;
    
    private String tenPhong;
    
    private Date ngayTruc;
    
    private static final long serialVersionUID = 1L;
    
    
    public String getNhanCaTruc() {
		return nhanCaTruc;
	}

	public void setNhanCaTruc(String nhanCaTruc) {
		this.nhanCaTruc = nhanCaTruc;
	}

	public String getTenPhong() {
		return tenPhong;
	}

	public void setTenPhong(String tenPhong) {
		this.tenPhong = tenPhong;
	}

	public Date getNgayTruc() {
		return ngayTruc;
	}

	public void setNgayTruc(Date ngayTruc) {
		this.ngayTruc = ngayTruc;
	}

    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table NOC_DANH_GIA_CSHT
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
	

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.ID
     *
     * @return the value of NOC_DANH_GIA_CSHT.ID
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.ID
     *
     * @param id the value for NOC_DANH_GIA_CSHT.ID
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.ID_CA_TRUC
     *
     * @return the value of NOC_DANH_GIA_CSHT.ID_CA_TRUC
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public Integer getIdCaTruc() {
        return idCaTruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.ID_CA_TRUC
     *
     * @param idCaTruc the value for NOC_DANH_GIA_CSHT.ID_CA_TRUC
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setIdCaTruc(Integer idCaTruc) {
        this.idCaTruc = idCaTruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.MA_PHONG
     *
     * @return the value of NOC_DANH_GIA_CSHT.MA_PHONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getMaPhong() {
        return maPhong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.MA_PHONG
     *
     * @param maPhong the value for NOC_DANH_GIA_CSHT.MA_PHONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setMaPhong(String maPhong) {
        this.maPhong = maPhong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.TO_UCTT
     *
     * @return the value of NOC_DANH_GIA_CSHT.TO_UCTT
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getToUctt() {
        return toUctt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.TO_UCTT
     *
     * @param toUctt the value for NOC_DANH_GIA_CSHT.TO_UCTT
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setToUctt(String toUctt) {
        this.toUctt = toUctt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.HE_THONG
     *
     * @return the value of NOC_DANH_GIA_CSHT.HE_THONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getHeThong() {
        return heThong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.HE_THONG
     *
     * @param heThong the value for NOC_DANH_GIA_CSHT.HE_THONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setHeThong(String heThong) {
        this.heThong = heThong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.SO_LUONG
     *
     * @return the value of NOC_DANH_GIA_CSHT.SO_LUONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getSoLuong() {
        return soLuong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.SO_LUONG
     *
     * @param soLuong the value for NOC_DANH_GIA_CSHT.SO_LUONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setSoLuong(String soLuong) {
        this.soLuong = soLuong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.DANH_GIA_TAI
     *
     * @return the value of NOC_DANH_GIA_CSHT.DANH_GIA_TAI
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getDanhGiaTai() {
        return danhGiaTai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.DANH_GIA_TAI
     *
     * @param danhGiaTai the value for NOC_DANH_GIA_CSHT.DANH_GIA_TAI
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setDanhGiaTai(String danhGiaTai) {
        this.danhGiaTai = danhGiaTai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.HT_TAI_CAO
     *
     * @return the value of NOC_DANH_GIA_CSHT.HT_TAI_CAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getHtTaiCao() {
        return htTaiCao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.HT_TAI_CAO
     *
     * @param htTaiCao the value for NOC_DANH_GIA_CSHT.HT_TAI_CAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setHtTaiCao(String htTaiCao) {
        this.htTaiCao = htTaiCao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.HOAT_DONG
     *
     * @return the value of NOC_DANH_GIA_CSHT.HOAT_DONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getHoatDong() {
        return hoatDong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.HOAT_DONG
     *
     * @param hoatDong the value for NOC_DANH_GIA_CSHT.HOAT_DONG
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setHoatDong(String hoatDong) {
        this.hoatDong = hoatDong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.DE_XUAT
     *
     * @return the value of NOC_DANH_GIA_CSHT.DE_XUAT
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getDeXuat() {
        return deXuat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.DE_XUAT
     *
     * @param deXuat the value for NOC_DANH_GIA_CSHT.DE_XUAT
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setDeXuat(String deXuat) {
        this.deXuat = deXuat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.GHI_CHU
     *
     * @return the value of NOC_DANH_GIA_CSHT.GHI_CHU
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getGhiChu() {
        return ghiChu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.GHI_CHU
     *
     * @param ghiChu the value for NOC_DANH_GIA_CSHT.GHI_CHU
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.NGUOI_TAO
     *
     * @return the value of NOC_DANH_GIA_CSHT.NGUOI_TAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getNguoiTao() {
        return nguoiTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.NGUOI_TAO
     *
     * @param nguoiTao the value for NOC_DANH_GIA_CSHT.NGUOI_TAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setNguoiTao(String nguoiTao) {
        this.nguoiTao = nguoiTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.NGAY_TAO
     *
     * @return the value of NOC_DANH_GIA_CSHT.NGAY_TAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public Date getNgayTao() {
        return ngayTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.NGAY_TAO
     *
     * @param ngayTao the value for NOC_DANH_GIA_CSHT.NGAY_TAO
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.NGUOI_SUA
     *
     * @return the value of NOC_DANH_GIA_CSHT.NGUOI_SUA
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getNguoiSua() {
        return nguoiSua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.NGUOI_SUA
     *
     * @param nguoiSua the value for NOC_DANH_GIA_CSHT.NGUOI_SUA
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setNguoiSua(String nguoiSua) {
        this.nguoiSua = nguoiSua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.NGAY_SUA
     *
     * @return the value of NOC_DANH_GIA_CSHT.NGAY_SUA
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public Date getNgaySua() {
        return ngaySua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.NGAY_SUA
     *
     * @param ngaySua the value for NOC_DANH_GIA_CSHT.NGAY_SUA
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setNgaySua(Date ngaySua) {
        this.ngaySua = ngaySua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.GUI_CNOC
     *
     * @return the value of NOC_DANH_GIA_CSHT.GUI_CNOC
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getGuiCnoc() {
        return guiCnoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.GUI_CNOC
     *
     * @param guiCnoc the value for NOC_DANH_GIA_CSHT.GUI_CNOC
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setGuiCnoc(String guiCnoc) {
        this.guiCnoc = guiCnoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_DANH_GIA_CSHT.KEY_SHARING
     *
     * @return the value of NOC_DANH_GIA_CSHT.KEY_SHARING
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public String getKeySharing() {
        return keySharing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_DANH_GIA_CSHT.KEY_SHARING
     *
     * @param keySharing the value for NOC_DANH_GIA_CSHT.KEY_SHARING
     *
     * @ibatorgenerated Fri Mar 18 13:38:21 ICT 2016
     */
    public void setKeySharing(String keySharing) {
        this.keySharing = keySharing;
    }
    
    
    
    public String getNgayTrucStr() {
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
		if(ngayTruc != null)
			return df.format(ngayTruc);
		else
			return null;
	}
    
    
}