package vo.bts;

import java.io.Serializable;
import java.util.Date;

public class NocFileAttachment implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.ID
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.ID_LINK
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private Integer idLink;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.FUNCTION_NAME
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private String functionName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.FILE_NAME
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private String fileName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.FILE_PATH
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private String filePath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.FILE_IMAGE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private String fileImage;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.DESCRIPTION
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.ORDERING
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private Integer ordering;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.PATH_ON_WEB
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private String pathOnWeb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.ID_IMAGE_TYPE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private String idImageType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.CREATED_DATE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private Date createdDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_FILE_ATTACHMENT.MODIFIED_DATE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private Date modifiedDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table NOC_FILE_ATTACHMENT
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.ID
     *
     * @return the value of NOC_FILE_ATTACHMENT.ID
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.ID
     *
     * @param id the value for NOC_FILE_ATTACHMENT.ID
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.ID_LINK
     *
     * @return the value of NOC_FILE_ATTACHMENT.ID_LINK
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public Integer getIdLink() {
        return idLink;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.ID_LINK
     *
     * @param idLink the value for NOC_FILE_ATTACHMENT.ID_LINK
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setIdLink(Integer idLink) {
        this.idLink = idLink;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.FUNCTION_NAME
     *
     * @return the value of NOC_FILE_ATTACHMENT.FUNCTION_NAME
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.FUNCTION_NAME
     *
     * @param functionName the value for NOC_FILE_ATTACHMENT.FUNCTION_NAME
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.FILE_NAME
     *
     * @return the value of NOC_FILE_ATTACHMENT.FILE_NAME
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.FILE_NAME
     *
     * @param fileName the value for NOC_FILE_ATTACHMENT.FILE_NAME
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.FILE_PATH
     *
     * @return the value of NOC_FILE_ATTACHMENT.FILE_PATH
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.FILE_PATH
     *
     * @param filePath the value for NOC_FILE_ATTACHMENT.FILE_PATH
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.FILE_IMAGE
     *
     * @return the value of NOC_FILE_ATTACHMENT.FILE_IMAGE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public String getFileImage() {
        return fileImage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.FILE_IMAGE
     *
     * @param fileImage the value for NOC_FILE_ATTACHMENT.FILE_IMAGE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setFileImage(String fileImage) {
        this.fileImage = fileImage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.DESCRIPTION
     *
     * @return the value of NOC_FILE_ATTACHMENT.DESCRIPTION
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.DESCRIPTION
     *
     * @param description the value for NOC_FILE_ATTACHMENT.DESCRIPTION
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.ORDERING
     *
     * @return the value of NOC_FILE_ATTACHMENT.ORDERING
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public Integer getOrdering() {
        return ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.ORDERING
     *
     * @param ordering the value for NOC_FILE_ATTACHMENT.ORDERING
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.PATH_ON_WEB
     *
     * @return the value of NOC_FILE_ATTACHMENT.PATH_ON_WEB
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public String getPathOnWeb() {
        return pathOnWeb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.PATH_ON_WEB
     *
     * @param pathOnWeb the value for NOC_FILE_ATTACHMENT.PATH_ON_WEB
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setPathOnWeb(String pathOnWeb) {
        this.pathOnWeb = pathOnWeb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.ID_IMAGE_TYPE
     *
     * @return the value of NOC_FILE_ATTACHMENT.ID_IMAGE_TYPE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public String getIdImageType() {
        return idImageType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.ID_IMAGE_TYPE
     *
     * @param idImageType the value for NOC_FILE_ATTACHMENT.ID_IMAGE_TYPE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setIdImageType(String idImageType) {
        this.idImageType = idImageType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.CREATED_DATE
     *
     * @return the value of NOC_FILE_ATTACHMENT.CREATED_DATE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.CREATED_DATE
     *
     * @param createdDate the value for NOC_FILE_ATTACHMENT.CREATED_DATE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_FILE_ATTACHMENT.MODIFIED_DATE
     *
     * @return the value of NOC_FILE_ATTACHMENT.MODIFIED_DATE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_FILE_ATTACHMENT.MODIFIED_DATE
     *
     * @param modifiedDate the value for NOC_FILE_ATTACHMENT.MODIFIED_DATE
     *
     * @ibatorgenerated Mon Dec 14 15:36:17 ICT 2015
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}