package vo.bts;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class NocRaVaoTram implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.ID
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.MA_PHONG
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String maPhong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.CA_TRUC
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private Integer caTruc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.NGUOI_RAVAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String nguoiRavao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.TG_VAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private Date tgVao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.TG_RA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private Date tgRa;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.CCDC_VAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String ccdcVao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.CCDC_RA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String ccdcRa;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.MUC_DICH
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String mucDich;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.VAN_BAN_PD
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String vanBanPd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.KET_QUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String ketQua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.TON_TAI
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String tonTai;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.NGUOI_TAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String nguoiTao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.NGAY_TAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private Date ngayTao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.NGUOI_SUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private String nguoiSua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_RA_VAO_NHA_TRAM.NGAY_SUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private Date ngaySua;

    
    
    private String nhanCaTruc;
    
    
    private String tenPhong;
    
    private Date ngayTruc;
    
    
    public Date getNgayTruc() {
		return ngayTruc;
	}

	public void setNgayTruc(Date ngayTruc) {
		this.ngayTruc = ngayTruc;
	}

	
	
	public String getNhanCaTruc() {
		return nhanCaTruc;
	}

	public void setNhanCaTruc(String nhanCaTruc) {
		this.nhanCaTruc = nhanCaTruc;
	}

	public String getTenPhong() {
		return tenPhong;
	}

	public void setTenPhong(String tenPhong) {
		this.tenPhong = tenPhong;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table NOC_RA_VAO_NHA_TRAM
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.ID
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.ID
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    
    
    public String getNgayTrucStr() {
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
		if(ngayTruc != null)
			return df.format(ngayTruc);
		else
			return null;
	}
    
    
    
    
    public String getTgVaoStr() {
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
		if(tgVao != null)
			return df.format(tgVao);
		else
			return null;
	}
    
    
    public String getTgRaStr() {
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
		if(tgRa != null)
			return df.format(tgRa);
		else
			return null;
	}
    
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.ID
     *
     * @param id the value for NOC_RA_VAO_NHA_TRAM.ID
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.MA_PHONG
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.MA_PHONG
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getMaPhong() {
        return maPhong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.MA_PHONG
     *
     * @param maPhong the value for NOC_RA_VAO_NHA_TRAM.MA_PHONG
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setMaPhong(String maPhong) {
        this.maPhong = maPhong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.CA_TRUC
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.CA_TRUC
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public Integer getCaTruc() {
        return caTruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.CA_TRUC
     *
     * @param caTruc the value for NOC_RA_VAO_NHA_TRAM.CA_TRUC
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setCaTruc(Integer caTruc) {
        this.caTruc = caTruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.NGUOI_RAVAO
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.NGUOI_RAVAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getNguoiRavao() {
        return nguoiRavao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.NGUOI_RAVAO
     *
     * @param nguoiRavao the value for NOC_RA_VAO_NHA_TRAM.NGUOI_RAVAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setNguoiRavao(String nguoiRavao) {
        this.nguoiRavao = nguoiRavao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.TG_VAO
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.TG_VAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public Date getTgVao() {
        return tgVao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.TG_VAO
     *
     * @param tgVao the value for NOC_RA_VAO_NHA_TRAM.TG_VAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setTgVao(Date tgVao) {
        this.tgVao = tgVao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.TG_RA
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.TG_RA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public Date getTgRa() {
        return tgRa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.TG_RA
     *
     * @param tgRa the value for NOC_RA_VAO_NHA_TRAM.TG_RA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setTgRa(Date tgRa) {
        this.tgRa = tgRa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.CCDC_VAO
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.CCDC_VAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getCcdcVao() {
        return ccdcVao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.CCDC_VAO
     *
     * @param ccdcVao the value for NOC_RA_VAO_NHA_TRAM.CCDC_VAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setCcdcVao(String ccdcVao) {
        this.ccdcVao = ccdcVao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.CCDC_RA
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.CCDC_RA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getCcdcRa() {
        return ccdcRa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.CCDC_RA
     *
     * @param ccdcRa the value for NOC_RA_VAO_NHA_TRAM.CCDC_RA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setCcdcRa(String ccdcRa) {
        this.ccdcRa = ccdcRa;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.MUC_DICH
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.MUC_DICH
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getMucDich() {
        return mucDich;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.MUC_DICH
     *
     * @param mucDich the value for NOC_RA_VAO_NHA_TRAM.MUC_DICH
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setMucDich(String mucDich) {
        this.mucDich = mucDich;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.VAN_BAN_PD
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.VAN_BAN_PD
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getVanBanPd() {
        return vanBanPd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.VAN_BAN_PD
     *
     * @param vanBanPd the value for NOC_RA_VAO_NHA_TRAM.VAN_BAN_PD
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setVanBanPd(String vanBanPd) {
        this.vanBanPd = vanBanPd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.KET_QUA
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.KET_QUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getKetQua() {
        return ketQua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.KET_QUA
     *
     * @param ketQua the value for NOC_RA_VAO_NHA_TRAM.KET_QUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setKetQua(String ketQua) {
        this.ketQua = ketQua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.TON_TAI
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.TON_TAI
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getTonTai() {
        return tonTai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.TON_TAI
     *
     * @param tonTai the value for NOC_RA_VAO_NHA_TRAM.TON_TAI
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setTonTai(String tonTai) {
        this.tonTai = tonTai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.NGUOI_TAO
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.NGUOI_TAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getNguoiTao() {
        return nguoiTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.NGUOI_TAO
     *
     * @param nguoiTao the value for NOC_RA_VAO_NHA_TRAM.NGUOI_TAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setNguoiTao(String nguoiTao) {
        this.nguoiTao = nguoiTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.NGAY_TAO
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.NGAY_TAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public Date getNgayTao() {
        return ngayTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.NGAY_TAO
     *
     * @param ngayTao the value for NOC_RA_VAO_NHA_TRAM.NGAY_TAO
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.NGUOI_SUA
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.NGUOI_SUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public String getNguoiSua() {
        return nguoiSua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.NGUOI_SUA
     *
     * @param nguoiSua the value for NOC_RA_VAO_NHA_TRAM.NGUOI_SUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setNguoiSua(String nguoiSua) {
        this.nguoiSua = nguoiSua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_RA_VAO_NHA_TRAM.NGAY_SUA
     *
     * @return the value of NOC_RA_VAO_NHA_TRAM.NGAY_SUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public Date getNgaySua() {
        return ngaySua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_RA_VAO_NHA_TRAM.NGAY_SUA
     *
     * @param ngaySua the value for NOC_RA_VAO_NHA_TRAM.NGAY_SUA
     *
     * @ibatorgenerated Thu Dec 10 09:13:26 ICT 2015
     */
    public void setNgaySua(Date ngaySua) {
        this.ngaySua = ngaySua;
    }
    
    public String getDoiTac() {
		return doiTac;
	}

	public void setDoiTac(String doiTac) {
		this.doiTac = doiTac;
	}

	public String getSite() {
		return site;
	}

	public String getSdtNguoiRaVao() {
		return sdtNguoiRaVao;
	}

	public void setSdtNguoiRaVao(String sdtNguoiRaVao) {
		this.sdtNguoiRaVao = sdtNguoiRaVao;
	}

	public String getNguoiQuanLy() {
		return nguoiQuanLy;
	}

	public void setNguoiQuanLy(String nguoiQuanLy) {
		this.nguoiQuanLy = nguoiQuanLy;
	}

	public String getSdtNguoiQuanLy() {
		return sdtNguoiQuanLy;
	}

	public void setSdtNguoiQuanLy(String sdtNguoiQuanLy) {
		this.sdtNguoiQuanLy = sdtNguoiQuanLy;
	}

	public void setSite(String site) {
		this.site = site;
	}

	private String doiTac;
    private String site;
    
    private String sdtNguoiRaVao;
    private String nguoiQuanLy;
    private String sdtNguoiQuanLy;
    
    public String getConfirmUser() {
		return confirmUser;
	}

	public void setConfirmUser(String confirmUser) {
		this.confirmUser = confirmUser;
	}

	public Date getConfirmTime() {
		return confirmTime;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

	private String confirmUser;
    private Date confirmTime;


	public String getConfirmTimeStr() {
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
		if (confirmTime != null)
			return df.format(confirmTime);
		else
			return null;
	}
}