package vo.bts;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class NocTDMangLuoi implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.ID
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.ID_CA_TRUC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private Integer idCaTruc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.MA_PHONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String maPhong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.LOAI_HOAT_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String loaiHoatDong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.TEN_TONG_DAI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String tenTongDai;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.TEN_TAI_SAN
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String tenTaiSan;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.TG_BAT_DAU
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private Date tgBatDau;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.TG_KET_THUC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private Date tgKetThuc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_TAC_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String nguoiTacDong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_CHU_TRI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String nguoiChuTri;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_GIAM_SAT
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String nguoiGiamSat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_HO_TRO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String nguoiHoTro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_CHI_DAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String nguoiChiDao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.VAN_BAN_PHE_DUYET
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String vanBanPheDuyet;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.KET_QUA_TAC_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String ketQuaTacDong;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.TON_TAI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String tonTai;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.GUI_CNOC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String guiCnoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.KEY_SHARING
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String keySharing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_TAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String nguoiTao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGAY_TAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private Date ngayTao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_SUA
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private String nguoiSua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column NOC_TAC_DONG_MANG_LUOI.NGAY_SUA
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    private Date ngaySua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table NOC_TAC_DONG_MANG_LUOI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    
    
    private String nhanCaTruc;
    
    private String tenPhong;
    
    private Date ngayTruc;
    
    
    public String getNhanCaTruc() {
		return nhanCaTruc;
	}

	public void setNhanCaTruc(String nhanCaTruc) {
		this.nhanCaTruc = nhanCaTruc;
	}

	public String getTenPhong() {
		return tenPhong;
	}

	public void setTenPhong(String tenPhong) {
		this.tenPhong = tenPhong;
	}

    
	public Date getNgayTruc() {
		return ngayTruc;
	}

	public void setNgayTruc(Date ngayTruc) {
		this.ngayTruc = ngayTruc;
	}

	public String getNgayTrucStr() {
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
		if(ngayTruc != null)
			return df.format(ngayTruc);
		else
			return null;
	}
	
	 public String getTgBatDauStr() {
			SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
			if(tgBatDau != null)
				return df.format(tgBatDau);
			else
				return null;
		}
	    
	    
	public String getTgKetThucStr() {
		SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
		if (tgKetThuc != null)
			return df.format(tgKetThuc);
		else
			return null;
	}
	    
	    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.ID
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.ID
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.ID
     *
     * @param id the value for NOC_TAC_DONG_MANG_LUOI.ID
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.ID_CA_TRUC
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.ID_CA_TRUC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public Integer getIdCaTruc() {
        return idCaTruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.ID_CA_TRUC
     *
     * @param idCaTruc the value for NOC_TAC_DONG_MANG_LUOI.ID_CA_TRUC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setIdCaTruc(Integer idCaTruc) {
        this.idCaTruc = idCaTruc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.MA_PHONG
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.MA_PHONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getMaPhong() {
        return maPhong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.MA_PHONG
     *
     * @param maPhong the value for NOC_TAC_DONG_MANG_LUOI.MA_PHONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setMaPhong(String maPhong) {
        this.maPhong = maPhong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.LOAI_HOAT_DONG
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.LOAI_HOAT_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getLoaiHoatDong() {
        return loaiHoatDong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.LOAI_HOAT_DONG
     *
     * @param loaiHoatDong the value for NOC_TAC_DONG_MANG_LUOI.LOAI_HOAT_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setLoaiHoatDong(String loaiHoatDong) {
        this.loaiHoatDong = loaiHoatDong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.TEN_TONG_DAI
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.TEN_TONG_DAI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getTenTongDai() {
        return tenTongDai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.TEN_TONG_DAI
     *
     * @param tenTongDai the value for NOC_TAC_DONG_MANG_LUOI.TEN_TONG_DAI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setTenTongDai(String tenTongDai) {
        this.tenTongDai = tenTongDai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.TEN_TAI_SAN
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.TEN_TAI_SAN
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getTenTaiSan() {
        return tenTaiSan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.TEN_TAI_SAN
     *
     * @param tenTaiSan the value for NOC_TAC_DONG_MANG_LUOI.TEN_TAI_SAN
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setTenTaiSan(String tenTaiSan) {
        this.tenTaiSan = tenTaiSan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.TG_BAT_DAU
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.TG_BAT_DAU
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public Date getTgBatDau() {
        return tgBatDau;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.TG_BAT_DAU
     *
     * @param tgBatDau the value for NOC_TAC_DONG_MANG_LUOI.TG_BAT_DAU
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setTgBatDau(Date tgBatDau) {
        this.tgBatDau = tgBatDau;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.TG_KET_THUC
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.TG_KET_THUC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public Date getTgKetThuc() {
        return tgKetThuc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.TG_KET_THUC
     *
     * @param tgKetThuc the value for NOC_TAC_DONG_MANG_LUOI.TG_KET_THUC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setTgKetThuc(Date tgKetThuc) {
        this.tgKetThuc = tgKetThuc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_TAC_DONG
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGUOI_TAC_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getNguoiTacDong() {
        return nguoiTacDong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_TAC_DONG
     *
     * @param nguoiTacDong the value for NOC_TAC_DONG_MANG_LUOI.NGUOI_TAC_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNguoiTacDong(String nguoiTacDong) {
        this.nguoiTacDong = nguoiTacDong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_CHU_TRI
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGUOI_CHU_TRI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getNguoiChuTri() {
        return nguoiChuTri;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_CHU_TRI
     *
     * @param nguoiChuTri the value for NOC_TAC_DONG_MANG_LUOI.NGUOI_CHU_TRI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNguoiChuTri(String nguoiChuTri) {
        this.nguoiChuTri = nguoiChuTri;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_GIAM_SAT
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGUOI_GIAM_SAT
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getNguoiGiamSat() {
        return nguoiGiamSat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_GIAM_SAT
     *
     * @param nguoiGiamSat the value for NOC_TAC_DONG_MANG_LUOI.NGUOI_GIAM_SAT
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNguoiGiamSat(String nguoiGiamSat) {
        this.nguoiGiamSat = nguoiGiamSat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_HO_TRO
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGUOI_HO_TRO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getNguoiHoTro() {
        return nguoiHoTro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_HO_TRO
     *
     * @param nguoiHoTro the value for NOC_TAC_DONG_MANG_LUOI.NGUOI_HO_TRO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNguoiHoTro(String nguoiHoTro) {
        this.nguoiHoTro = nguoiHoTro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_CHI_DAO
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGUOI_CHI_DAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getNguoiChiDao() {
        return nguoiChiDao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_CHI_DAO
     *
     * @param nguoiChiDao the value for NOC_TAC_DONG_MANG_LUOI.NGUOI_CHI_DAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNguoiChiDao(String nguoiChiDao) {
        this.nguoiChiDao = nguoiChiDao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.VAN_BAN_PHE_DUYET
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.VAN_BAN_PHE_DUYET
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getVanBanPheDuyet() {
        return vanBanPheDuyet;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.VAN_BAN_PHE_DUYET
     *
     * @param vanBanPheDuyet the value for NOC_TAC_DONG_MANG_LUOI.VAN_BAN_PHE_DUYET
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setVanBanPheDuyet(String vanBanPheDuyet) {
        this.vanBanPheDuyet = vanBanPheDuyet;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.KET_QUA_TAC_DONG
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.KET_QUA_TAC_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getKetQuaTacDong() {
        return ketQuaTacDong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.KET_QUA_TAC_DONG
     *
     * @param ketQuaTacDong the value for NOC_TAC_DONG_MANG_LUOI.KET_QUA_TAC_DONG
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setKetQuaTacDong(String ketQuaTacDong) {
        this.ketQuaTacDong = ketQuaTacDong;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.TON_TAI
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.TON_TAI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getTonTai() {
        return tonTai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.TON_TAI
     *
     * @param tonTai the value for NOC_TAC_DONG_MANG_LUOI.TON_TAI
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setTonTai(String tonTai) {
        this.tonTai = tonTai;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.GUI_CNOC
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.GUI_CNOC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getGuiCnoc() {
        return guiCnoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.GUI_CNOC
     *
     * @param guiCnoc the value for NOC_TAC_DONG_MANG_LUOI.GUI_CNOC
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setGuiCnoc(String guiCnoc) {
        this.guiCnoc = guiCnoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.KEY_SHARING
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.KEY_SHARING
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getKeySharing() {
        return keySharing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.KEY_SHARING
     *
     * @param keySharing the value for NOC_TAC_DONG_MANG_LUOI.KEY_SHARING
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setKeySharing(String keySharing) {
        this.keySharing = keySharing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_TAO
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGUOI_TAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getNguoiTao() {
        return nguoiTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_TAO
     *
     * @param nguoiTao the value for NOC_TAC_DONG_MANG_LUOI.NGUOI_TAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNguoiTao(String nguoiTao) {
        this.nguoiTao = nguoiTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGAY_TAO
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGAY_TAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public Date getNgayTao() {
        return ngayTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGAY_TAO
     *
     * @param ngayTao the value for NOC_TAC_DONG_MANG_LUOI.NGAY_TAO
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_SUA
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGUOI_SUA
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public String getNguoiSua() {
        return nguoiSua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGUOI_SUA
     *
     * @param nguoiSua the value for NOC_TAC_DONG_MANG_LUOI.NGUOI_SUA
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNguoiSua(String nguoiSua) {
        this.nguoiSua = nguoiSua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column NOC_TAC_DONG_MANG_LUOI.NGAY_SUA
     *
     * @return the value of NOC_TAC_DONG_MANG_LUOI.NGAY_SUA
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public Date getNgaySua() {
        return ngaySua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column NOC_TAC_DONG_MANG_LUOI.NGAY_SUA
     *
     * @param ngaySua the value for NOC_TAC_DONG_MANG_LUOI.NGAY_SUA
     *
     * @ibatorgenerated Wed Dec 16 09:00:12 ICT 2015
     */
    public void setNgaySua(Date ngaySua) {
        this.ngaySua = ngaySua;
    }
}