package vo.bts;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class RalarmRogActiveCisco implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.NE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String ne;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.SITE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String site;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CELLID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String cellid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.DIP
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String dip;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.SDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date sdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.EDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date edate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.MO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String mo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String alarmType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.SEVERITY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String severity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_NAME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String alarmName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_INFO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String alarmInfo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Integer alarmId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String alarmMappingId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_NAME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String alarmMappingName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.STATUS_VIEW
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String statusView;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_STATUS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String ackStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_TIME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date ackTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_USER
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String ackUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.SHIFT_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Integer shiftId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.DISTRICT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String district;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.DEPT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String dept;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String causeby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ACTION_PROCESS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String actionProcess;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY_SYS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String causebySys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.DESCRIPTION
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.NETWORK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String network;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.VENDOR
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String vendor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.BSCPORT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String bscport;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.BTSPORT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String btsport;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.TEAM
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String team;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.GROUPS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String groups;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.NOTE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String note;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CREATED_BY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String createdBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CREATE_DATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.MODIFIED_BY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String modifiedBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.MODIFY_DATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date modifyDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.NE_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String neType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.REP_COUNT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Integer repCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CH_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String chType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.OBJECT_REFERENCE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String objectReference;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.SLOT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Integer slot;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.FM_ALARMID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Integer fmAlarmid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.OBJ_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String objType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CLR_STATUS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String clrStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.PROVINCE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.EVTTYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String evttype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.RACK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String rack;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.SUBRACK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String subrack;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.IS_SMS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String isSms;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.USER_ACK_TIME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date userAckTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.TRANS_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String transType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.VENDOR_TRANS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String vendorTrans;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE_SUB
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String alarmTypeSub;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.SITE_IBC
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String siteIbc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.MD_SDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date mdSdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.MD_EDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date mdEdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.VIEW_1090
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String view1090;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.REGION
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String region;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALERTED_SOUND
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String alertedSound;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSED_FINISH
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String causedFinish;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.UK_ALARM_KEY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String ukAlarmKey;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.CREATED_DATE_CHECK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date createdDateCheck;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_KEY_ERICSSON
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String alarmKeyEricsson;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.TG_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private Date tgChuyen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.PHUONG_THUC_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String phuongThucChuyen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.NGUOI_XU_LY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String nguoiXuLy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.TIEN_TRINH_XU_LY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String tienTrinhXuLy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.KET_QUA
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String ketQua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.DE_XUAT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String deXuat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.DANH_GIA_SLA
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String danhGiaSla;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.STATUS_PROCESS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String statusProcess;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.NGUOI_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String nguoiChuyen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.HE_THONG_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String heThongChuyen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.IS_MLL
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String isMll;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column R_ALARM_LOG_ACTIVE_CISCO.NE_IP
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private String neIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table R_ALARM_LOG_ACTIVE_CISCO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ID
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ID
     *
     * @param id the value for R_ALARM_LOG_ACTIVE_CISCO.ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.NE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getNe() {
        return ne;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NE
     *
     * @param ne the value for R_ALARM_LOG_ACTIVE_CISCO.NE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setNe(String ne) {
        this.ne = ne;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SITE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.SITE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SITE
     *
     * @param site the value for R_ALARM_LOG_ACTIVE_CISCO.SITE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setSite(String site) {
        this.site = site;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CELLID
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CELLID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getCellid() {
        return cellid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CELLID
     *
     * @param cellid the value for R_ALARM_LOG_ACTIVE_CISCO.CELLID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setCellid(String cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DIP
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.DIP
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getDip() {
        return dip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DIP
     *
     * @param dip the value for R_ALARM_LOG_ACTIVE_CISCO.DIP
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setDip(String dip) {
        this.dip = dip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SDATE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.SDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SDATE
     *
     * @param sdate the value for R_ALARM_LOG_ACTIVE_CISCO.SDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.EDATE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.EDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getEdate() {
        return edate;
    }
    public String getEdateStr()
    {
    	if (edate!=null)
    		return (new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(edate));
    	return null;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.EDATE
     *
     * @param edate the value for R_ALARM_LOG_ACTIVE_CISCO.EDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setEdate(Date edate) {
        this.edate = edate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MO
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.MO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getMo() {
        return mo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MO
     *
     * @param mo the value for R_ALARM_LOG_ACTIVE_CISCO.MO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setMo(String mo) {
        this.mo = mo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE
     *
     * @param alarmType the value for R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SEVERITY
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.SEVERITY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SEVERITY
     *
     * @param severity the value for R_ALARM_LOG_ACTIVE_CISCO.SEVERITY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setSeverity(String severity) {
        this.severity = severity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_NAME
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALARM_NAME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAlarmName() {
        return alarmName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_NAME
     *
     * @param alarmName the value for R_ALARM_LOG_ACTIVE_CISCO.ALARM_NAME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlarmName(String alarmName) {
        this.alarmName = alarmName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_INFO
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALARM_INFO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAlarmInfo() {
        return alarmInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_INFO
     *
     * @param alarmInfo the value for R_ALARM_LOG_ACTIVE_CISCO.ALARM_INFO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlarmInfo(String alarmInfo) {
        this.alarmInfo = alarmInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_ID
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALARM_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Integer getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_ID
     *
     * @param alarmId the value for R_ALARM_LOG_ACTIVE_CISCO.ALARM_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlarmId(Integer alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_ID
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAlarmMappingId() {
        return alarmMappingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_ID
     *
     * @param alarmMappingId the value for R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlarmMappingId(String alarmMappingId) {
        this.alarmMappingId = alarmMappingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_NAME
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_NAME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAlarmMappingName() {
        return alarmMappingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_NAME
     *
     * @param alarmMappingName the value for R_ALARM_LOG_ACTIVE_CISCO.ALARM_MAPPING_NAME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlarmMappingName(String alarmMappingName) {
        this.alarmMappingName = alarmMappingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.STATUS_VIEW
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.STATUS_VIEW
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getStatusView() {
        return statusView;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.STATUS_VIEW
     *
     * @param statusView the value for R_ALARM_LOG_ACTIVE_CISCO.STATUS_VIEW
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setStatusView(String statusView) {
        this.statusView = statusView;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_STATUS
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ACK_STATUS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAckStatus() {
        return ackStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_STATUS
     *
     * @param ackStatus the value for R_ALARM_LOG_ACTIVE_CISCO.ACK_STATUS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAckStatus(String ackStatus) {
        this.ackStatus = ackStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_TIME
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ACK_TIME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getAckTime() {
        return ackTime;
    }
    public String getAckTimeStr()
    {
    	if (ackTime!=null)
    		return (new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(ackTime));
    	return null;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_TIME
     *
     * @param ackTime the value for R_ALARM_LOG_ACTIVE_CISCO.ACK_TIME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAckTime(Date ackTime) {
        this.ackTime = ackTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_USER
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ACK_USER
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAckUser() {
        return ackUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ACK_USER
     *
     * @param ackUser the value for R_ALARM_LOG_ACTIVE_CISCO.ACK_USER
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAckUser(String ackUser) {
        this.ackUser = ackUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SHIFT_ID
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.SHIFT_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Integer getShiftId() {
        return shiftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SHIFT_ID
     *
     * @param shiftId the value for R_ALARM_LOG_ACTIVE_CISCO.SHIFT_ID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DISTRICT
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.DISTRICT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DISTRICT
     *
     * @param district the value for R_ALARM_LOG_ACTIVE_CISCO.DISTRICT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DEPT
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.DEPT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DEPT
     *
     * @param dept the value for R_ALARM_LOG_ACTIVE_CISCO.DEPT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getCauseby() {
        return causeby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY
     *
     * @param causeby the value for R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setCauseby(String causeby) {
        this.causeby = causeby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ACTION_PROCESS
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ACTION_PROCESS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getActionProcess() {
        return actionProcess;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ACTION_PROCESS
     *
     * @param actionProcess the value for R_ALARM_LOG_ACTIVE_CISCO.ACTION_PROCESS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setActionProcess(String actionProcess) {
        this.actionProcess = actionProcess;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY_SYS
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY_SYS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getCausebySys() {
        return causebySys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY_SYS
     *
     * @param causebySys the value for R_ALARM_LOG_ACTIVE_CISCO.CAUSEBY_SYS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setCausebySys(String causebySys) {
        this.causebySys = causebySys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DESCRIPTION
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.DESCRIPTION
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DESCRIPTION
     *
     * @param description the value for R_ALARM_LOG_ACTIVE_CISCO.DESCRIPTION
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NETWORK
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.NETWORK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getNetwork() {
        return network;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NETWORK
     *
     * @param network the value for R_ALARM_LOG_ACTIVE_CISCO.NETWORK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setNetwork(String network) {
        this.network = network;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.VENDOR
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.VENDOR
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.VENDOR
     *
     * @param vendor the value for R_ALARM_LOG_ACTIVE_CISCO.VENDOR
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.BSCPORT
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.BSCPORT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getBscport() {
        return bscport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.BSCPORT
     *
     * @param bscport the value for R_ALARM_LOG_ACTIVE_CISCO.BSCPORT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setBscport(String bscport) {
        this.bscport = bscport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.BTSPORT
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.BTSPORT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getBtsport() {
        return btsport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.BTSPORT
     *
     * @param btsport the value for R_ALARM_LOG_ACTIVE_CISCO.BTSPORT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setBtsport(String btsport) {
        this.btsport = btsport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.TEAM
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.TEAM
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.TEAM
     *
     * @param team the value for R_ALARM_LOG_ACTIVE_CISCO.TEAM
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setTeam(String team) {
        this.team = team;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.GROUPS
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.GROUPS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getGroups() {
        return groups;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.GROUPS
     *
     * @param groups the value for R_ALARM_LOG_ACTIVE_CISCO.GROUPS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setGroups(String groups) {
        this.groups = groups;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NOTE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.NOTE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NOTE
     *
     * @param note the value for R_ALARM_LOG_ACTIVE_CISCO.NOTE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CREATED_BY
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CREATED_BY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CREATED_BY
     *
     * @param createdBy the value for R_ALARM_LOG_ACTIVE_CISCO.CREATED_BY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CREATE_DATE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CREATE_DATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    public String getCreateDateStr()
    {
    	if (createDate!=null)
    		return (new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(createDate));
    	return null;
    }
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CREATE_DATE
     *
     * @param createDate the value for R_ALARM_LOG_ACTIVE_CISCO.CREATE_DATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MODIFIED_BY
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.MODIFIED_BY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MODIFIED_BY
     *
     * @param modifiedBy the value for R_ALARM_LOG_ACTIVE_CISCO.MODIFIED_BY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MODIFY_DATE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.MODIFY_DATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }
    public String getModifyDateStr()
    {
    	if (modifyDate!=null)
    		return (new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(modifyDate));
    	return null;
    }
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MODIFY_DATE
     *
     * @param modifyDate the value for R_ALARM_LOG_ACTIVE_CISCO.MODIFY_DATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NE_TYPE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.NE_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getNeType() {
        return neType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NE_TYPE
     *
     * @param neType the value for R_ALARM_LOG_ACTIVE_CISCO.NE_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setNeType(String neType) {
        this.neType = neType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.REP_COUNT
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.REP_COUNT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Integer getRepCount() {
        return repCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.REP_COUNT
     *
     * @param repCount the value for R_ALARM_LOG_ACTIVE_CISCO.REP_COUNT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setRepCount(Integer repCount) {
        this.repCount = repCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CH_TYPE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CH_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getChType() {
        return chType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CH_TYPE
     *
     * @param chType the value for R_ALARM_LOG_ACTIVE_CISCO.CH_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setChType(String chType) {
        this.chType = chType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.OBJECT_REFERENCE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.OBJECT_REFERENCE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getObjectReference() {
        return objectReference;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.OBJECT_REFERENCE
     *
     * @param objectReference the value for R_ALARM_LOG_ACTIVE_CISCO.OBJECT_REFERENCE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setObjectReference(String objectReference) {
        this.objectReference = objectReference;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SLOT
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.SLOT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Integer getSlot() {
        return slot;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SLOT
     *
     * @param slot the value for R_ALARM_LOG_ACTIVE_CISCO.SLOT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setSlot(Integer slot) {
        this.slot = slot;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.FM_ALARMID
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.FM_ALARMID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Integer getFmAlarmid() {
        return fmAlarmid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.FM_ALARMID
     *
     * @param fmAlarmid the value for R_ALARM_LOG_ACTIVE_CISCO.FM_ALARMID
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setFmAlarmid(Integer fmAlarmid) {
        this.fmAlarmid = fmAlarmid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.OBJ_TYPE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.OBJ_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getObjType() {
        return objType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.OBJ_TYPE
     *
     * @param objType the value for R_ALARM_LOG_ACTIVE_CISCO.OBJ_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setObjType(String objType) {
        this.objType = objType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CLR_STATUS
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CLR_STATUS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getClrStatus() {
        return clrStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CLR_STATUS
     *
     * @param clrStatus the value for R_ALARM_LOG_ACTIVE_CISCO.CLR_STATUS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setClrStatus(String clrStatus) {
        this.clrStatus = clrStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.PROVINCE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.PROVINCE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.PROVINCE
     *
     * @param province the value for R_ALARM_LOG_ACTIVE_CISCO.PROVINCE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.EVTTYPE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.EVTTYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getEvttype() {
        return evttype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.EVTTYPE
     *
     * @param evttype the value for R_ALARM_LOG_ACTIVE_CISCO.EVTTYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setEvttype(String evttype) {
        this.evttype = evttype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.RACK
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.RACK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getRack() {
        return rack;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.RACK
     *
     * @param rack the value for R_ALARM_LOG_ACTIVE_CISCO.RACK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setRack(String rack) {
        this.rack = rack;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SUBRACK
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.SUBRACK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getSubrack() {
        return subrack;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SUBRACK
     *
     * @param subrack the value for R_ALARM_LOG_ACTIVE_CISCO.SUBRACK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setSubrack(String subrack) {
        this.subrack = subrack;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.IS_SMS
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.IS_SMS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getIsSms() {
        return isSms;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.IS_SMS
     *
     * @param isSms the value for R_ALARM_LOG_ACTIVE_CISCO.IS_SMS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setIsSms(String isSms) {
        this.isSms = isSms;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.USER_ACK_TIME
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.USER_ACK_TIME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getUserAckTime() {
        return userAckTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.USER_ACK_TIME
     *
     * @param userAckTime the value for R_ALARM_LOG_ACTIVE_CISCO.USER_ACK_TIME
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setUserAckTime(Date userAckTime) {
        this.userAckTime = userAckTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.TRANS_TYPE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.TRANS_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.TRANS_TYPE
     *
     * @param transType the value for R_ALARM_LOG_ACTIVE_CISCO.TRANS_TYPE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setTransType(String transType) {
        this.transType = transType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.VENDOR_TRANS
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.VENDOR_TRANS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getVendorTrans() {
        return vendorTrans;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.VENDOR_TRANS
     *
     * @param vendorTrans the value for R_ALARM_LOG_ACTIVE_CISCO.VENDOR_TRANS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setVendorTrans(String vendorTrans) {
        this.vendorTrans = vendorTrans;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE_SUB
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE_SUB
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAlarmTypeSub() {
        return alarmTypeSub;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE_SUB
     *
     * @param alarmTypeSub the value for R_ALARM_LOG_ACTIVE_CISCO.ALARM_TYPE_SUB
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlarmTypeSub(String alarmTypeSub) {
        this.alarmTypeSub = alarmTypeSub;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SITE_IBC
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.SITE_IBC
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getSiteIbc() {
        return siteIbc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.SITE_IBC
     *
     * @param siteIbc the value for R_ALARM_LOG_ACTIVE_CISCO.SITE_IBC
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setSiteIbc(String siteIbc) {
        this.siteIbc = siteIbc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MD_SDATE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.MD_SDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getMdSdate() {
        return mdSdate;
    }
    public String getMdSdateStr()
    {
    	if (mdSdate!=null)
    		return (new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(mdSdate));
    	return null;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MD_SDATE
     *
     * @param mdSdate the value for R_ALARM_LOG_ACTIVE_CISCO.MD_SDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setMdSdate(Date mdSdate) {
        this.mdSdate = mdSdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MD_EDATE
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.MD_EDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getMdEdate() {
        return mdEdate;
    }
    public String getMdEdateStr()
    {
    	if (mdEdate!=null)
    		return (new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(mdEdate));
    	return null;
    }
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.MD_EDATE
     *
     * @param mdEdate the value for R_ALARM_LOG_ACTIVE_CISCO.MD_EDATE
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setMdEdate(Date mdEdate) {
        this.mdEdate = mdEdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.VIEW_1090
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.VIEW_1090
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getView1090() {
        return view1090;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.VIEW_1090
     *
     * @param view1090 the value for R_ALARM_LOG_ACTIVE_CISCO.VIEW_1090
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setView1090(String view1090) {
        this.view1090 = view1090;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.REGION
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.REGION
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.REGION
     *
     * @param region the value for R_ALARM_LOG_ACTIVE_CISCO.REGION
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALERTED_SOUND
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALERTED_SOUND
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAlertedSound() {
        return alertedSound;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALERTED_SOUND
     *
     * @param alertedSound the value for R_ALARM_LOG_ACTIVE_CISCO.ALERTED_SOUND
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlertedSound(String alertedSound) {
        this.alertedSound = alertedSound;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSED_FINISH
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CAUSED_FINISH
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getCausedFinish() {
        return causedFinish;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CAUSED_FINISH
     *
     * @param causedFinish the value for R_ALARM_LOG_ACTIVE_CISCO.CAUSED_FINISH
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setCausedFinish(String causedFinish) {
        this.causedFinish = causedFinish;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.UK_ALARM_KEY
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.UK_ALARM_KEY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getUkAlarmKey() {
        return ukAlarmKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.UK_ALARM_KEY
     *
     * @param ukAlarmKey the value for R_ALARM_LOG_ACTIVE_CISCO.UK_ALARM_KEY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setUkAlarmKey(String ukAlarmKey) {
        this.ukAlarmKey = ukAlarmKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CREATED_DATE_CHECK
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.CREATED_DATE_CHECK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getCreatedDateCheck() {
        return createdDateCheck;
    }
    public String getCreatedDateCheckStr()
    {
    	if (createdDateCheck!=null)
    		return (new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(createdDateCheck));
    	return null;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.CREATED_DATE_CHECK
     *
     * @param createdDateCheck the value for R_ALARM_LOG_ACTIVE_CISCO.CREATED_DATE_CHECK
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setCreatedDateCheck(Date createdDateCheck) {
        this.createdDateCheck = createdDateCheck;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_KEY_ERICSSON
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.ALARM_KEY_ERICSSON
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getAlarmKeyEricsson() {
        return alarmKeyEricsson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.ALARM_KEY_ERICSSON
     *
     * @param alarmKeyEricsson the value for R_ALARM_LOG_ACTIVE_CISCO.ALARM_KEY_ERICSSON
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setAlarmKeyEricsson(String alarmKeyEricsson) {
        this.alarmKeyEricsson = alarmKeyEricsson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.TG_CHUYEN
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.TG_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public Date getTgChuyen() {
        return tgChuyen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.TG_CHUYEN
     *
     * @param tgChuyen the value for R_ALARM_LOG_ACTIVE_CISCO.TG_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setTgChuyen(Date tgChuyen) {
        this.tgChuyen = tgChuyen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.PHUONG_THUC_CHUYEN
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.PHUONG_THUC_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getPhuongThucChuyen() {
        return phuongThucChuyen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.PHUONG_THUC_CHUYEN
     *
     * @param phuongThucChuyen the value for R_ALARM_LOG_ACTIVE_CISCO.PHUONG_THUC_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setPhuongThucChuyen(String phuongThucChuyen) {
        this.phuongThucChuyen = phuongThucChuyen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NGUOI_XU_LY
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.NGUOI_XU_LY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getNguoiXuLy() {
        return nguoiXuLy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NGUOI_XU_LY
     *
     * @param nguoiXuLy the value for R_ALARM_LOG_ACTIVE_CISCO.NGUOI_XU_LY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setNguoiXuLy(String nguoiXuLy) {
        this.nguoiXuLy = nguoiXuLy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.TIEN_TRINH_XU_LY
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.TIEN_TRINH_XU_LY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getTienTrinhXuLy() {
        return tienTrinhXuLy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.TIEN_TRINH_XU_LY
     *
     * @param tienTrinhXuLy the value for R_ALARM_LOG_ACTIVE_CISCO.TIEN_TRINH_XU_LY
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setTienTrinhXuLy(String tienTrinhXuLy) {
        this.tienTrinhXuLy = tienTrinhXuLy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.KET_QUA
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.KET_QUA
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getKetQua() {
        return ketQua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.KET_QUA
     *
     * @param ketQua the value for R_ALARM_LOG_ACTIVE_CISCO.KET_QUA
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setKetQua(String ketQua) {
        this.ketQua = ketQua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DE_XUAT
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.DE_XUAT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getDeXuat() {
        return deXuat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DE_XUAT
     *
     * @param deXuat the value for R_ALARM_LOG_ACTIVE_CISCO.DE_XUAT
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setDeXuat(String deXuat) {
        this.deXuat = deXuat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DANH_GIA_SLA
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.DANH_GIA_SLA
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getDanhGiaSla() {
        return danhGiaSla;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.DANH_GIA_SLA
     *
     * @param danhGiaSla the value for R_ALARM_LOG_ACTIVE_CISCO.DANH_GIA_SLA
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setDanhGiaSla(String danhGiaSla) {
        this.danhGiaSla = danhGiaSla;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.STATUS_PROCESS
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.STATUS_PROCESS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getStatusProcess() {
        return statusProcess;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.STATUS_PROCESS
     *
     * @param statusProcess the value for R_ALARM_LOG_ACTIVE_CISCO.STATUS_PROCESS
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setStatusProcess(String statusProcess) {
        this.statusProcess = statusProcess;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NGUOI_CHUYEN
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.NGUOI_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getNguoiChuyen() {
        return nguoiChuyen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NGUOI_CHUYEN
     *
     * @param nguoiChuyen the value for R_ALARM_LOG_ACTIVE_CISCO.NGUOI_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setNguoiChuyen(String nguoiChuyen) {
        this.nguoiChuyen = nguoiChuyen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.HE_THONG_CHUYEN
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.HE_THONG_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getHeThongChuyen() {
        return heThongChuyen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.HE_THONG_CHUYEN
     *
     * @param heThongChuyen the value for R_ALARM_LOG_ACTIVE_CISCO.HE_THONG_CHUYEN
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setHeThongChuyen(String heThongChuyen) {
        this.heThongChuyen = heThongChuyen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.IS_MLL
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.IS_MLL
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getIsMll() {
        return isMll;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.IS_MLL
     *
     * @param isMll the value for R_ALARM_LOG_ACTIVE_CISCO.IS_MLL
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setIsMll(String isMll) {
        this.isMll = isMll;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NE_IP
     *
     * @return the value of R_ALARM_LOG_ACTIVE_CISCO.NE_IP
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public String getNeIp() {
        return neIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column R_ALARM_LOG_ACTIVE_CISCO.NE_IP
     *
     * @param neIp the value for R_ALARM_LOG_ACTIVE_CISCO.NE_IP
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    public void setNeIp(String neIp) {
        this.neIp = neIp;
    }
}