package dao.bts;

import java.util.List;
import vo.bts.Bts_test;

public interface Bts_testDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_TEST
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    void insert(Bts_test record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_TEST
     *
     * @ibatorgenerated Fri Sep 14 15:10:23 ICT 2018
     */
    void insertSelective(Bts_test record);

    List <Bts_test> selectAll ();
    
    int delete (Integer id);

	Bts_test getBTS(Integer id);

	int editBTS(Bts_test bts);

	int addBTS(Bts_test bts);
    
}