package dao.bts;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vo.bts.BtsMetro;

public class BtsMetroDAOImpl extends SqlMapClientDaoSupport implements BtsMetroDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_METRO_TEST
     *
     * @ibatorgenerated Thu Sep 20 16:38:49 ICT 2018
     */
    public BtsMetroDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_METRO_TEST
     *
     * @ibatorgenerated Thu Sep 20 16:38:49 ICT 2018
     */
    public int deleteByPrimaryKey(Integer id) {
        BtsMetro key = new BtsMetro();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("BTS_METRO_TEST.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_METRO_TEST
     *
     * @ibatorgenerated Thu Sep 20 16:38:49 ICT 2018
     */
    public void insert(BtsMetro record) {
        getSqlMapClientTemplate().insert("BTS_METRO_TEST.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_METRO_TEST
     *
     * @ibatorgenerated Thu Sep 20 16:38:49 ICT 2018
     */
    public void insertSelective(BtsMetro record) {
        getSqlMapClientTemplate().insert("BTS_METRO_TEST.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_METRO_TEST
     *
     * @ibatorgenerated Thu Sep 20 16:38:49 ICT 2018
     */
    public BtsMetro selectByPrimaryKey(Integer id) {
        BtsMetro key = new BtsMetro();
        key.setId(id);
        BtsMetro record = (BtsMetro) getSqlMapClientTemplate().queryForObject("BTS_METRO_TEST.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_METRO_TEST
     *
     * @ibatorgenerated Thu Sep 20 16:38:49 ICT 2018
     */
    public int updateByPrimaryKeySelective(BtsMetro record) {
        int rows = getSqlMapClientTemplate().update("BTS_METRO_TEST.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table BTS_METRO_TEST
     *
     * @ibatorgenerated Thu Sep 20 16:38:49 ICT 2018
     */
    public int updateByPrimaryKey(BtsMetro record) {
        int rows = getSqlMapClientTemplate().update("BTS_METRO_TEST.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

	@Override
	public List<BtsMetro> getALL() {
		// TODO Auto-generated method stub
		Map<String, Object> map = new HashMap<String, Object>(); 
		map.put("p_DATA", null);
		return getSqlMapClientTemplate().queryForList("BTS_METRO_TEST.getBTS_Metro_List", map);
	}
}