package dao.bts;

import java.util.List;

import vo.bts.MDepartment;
import vo.bts.SYS_PARAMETER;

public interface MDepartmentDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 25 11:19:35 ICT 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 25 11:19:35 ICT 2012
     */
    void insert(MDepartment record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 25 11:19:35 ICT 2012
     */
    void insertSelective(MDepartment record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 25 11:19:35 ICT 2012
     */
    MDepartment selectByPrimaryKey(String deptCode);

    
    
    MDepartment selectMaByTenPhong(String tenPhong);
    
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 25 11:19:35 ICT 2012
     */
    int updateByPrimaryKeySelective(MDepartment record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table M_DEPARTMENT
     *
     * @ibatorgenerated Thu Oct 25 11:19:35 ICT 2012
     */
    int updateByPrimaryKey(MDepartment record);

	List<MDepartment> getUserList(String string);
	List<MDepartment> getPhongBanFilter(String maPhong, String tenVietTat, String tenPhong, String isEnable, String column, String order);
	MDepartment selectByID(String id);
	List<MDepartment> getPhongBanCha();
	List<MDepartment> getDepartmentList();

	List<MDepartment> getDepartmentDontId(String id);
	List<MDepartment> getDepartementBySystem();
	List<MDepartment> checkUserExcuteExits(String alarm, String user);

	List<MDepartment> distinctNhomPhongBan();

	int countPhongBanCha(Integer id);

	List<SYS_PARAMETER> getSystemListBySp();

	List<SYS_PARAMETER> titleDepartment();

	List<SYS_PARAMETER> getTrangThai();

	List<MDepartment> checkUserAlarmExits(String user);

	List<MDepartment> getDepartmentByEquipment();

	List<MDepartment> getDepartmentForShiftList(String stt);

	List<MDepartment> loadTeamByDepartment(String department);
	List<MDepartment> getVMDepartmentBacklog(String deptCode);
	List<MDepartment> getDepartmentOfUser(String userLogin);

	List<MDepartment> getGroupByDeptTeam(String dept, String team);
//07.01.2016: Lay danh sach the loai phong: CNOC, RNOC, Tổ UCTT
	List<SYS_PARAMETER> getLevelDept();
// Lấy danh sách phòng ban theo khu vực và câp đọ
	List<MDepartment> getDepartmentByRegion(String region, String stt,String isShift);

	List<MDepartment> getDepartmentByOnlyRegion(String region);

	List<String> getDistinctRegion();
	
	// lay danh sach phong ban theo phong ban cha va level dept
	List<MDepartment> getDepartmentByDeptCode_level(String dept, String level);

	
	//lay danh sach don vi anh huong: phong ban/quan huyen/thiet bi. phuc vu muc dich goi y tim kiem. AnhCTV:06/02/2017
	List<String> getDSDVAnhHuong();
	
	// Lay to vt va dai vt theo ma phong
	 List<MDepartment> getToVtAndDvt(String username);

}