package dao.bts;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import vo.bts.AlarmSLADailyReport7Day;
import vo.bts.DanhGiaSLASCAndMLL;
import vo.bts.NocBaocaoMatlienlac;
import vo.bts.NocDanhGiaCSHT;
import vo.bts.NocSCMangLuoi;
import vo.bts.QuanlyMatlienlac;
import vo.bts.SYS_PARAMETER;

public interface NocSCMangLuoiDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NOC_SU_CO_MANG_LUOI
     *
     * @ibatorgenerated Thu Dec 24 08:51:47 ICT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NOC_SU_CO_MANG_LUOI
     *
     * @ibatorgenerated Thu Dec 24 08:51:47 ICT 2015
     */
    void insert(NocSCMangLuoi record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NOC_SU_CO_MANG_LUOI
     *
     * @ibatorgenerated Thu Dec 24 08:51:47 ICT 2015
     */
    void insertSelective(NocSCMangLuoi record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NOC_SU_CO_MANG_LUOI
     *
     * @ibatorgenerated Thu Dec 24 08:51:47 ICT 2015
     */
    NocSCMangLuoi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NOC_SU_CO_MANG_LUOI
     *
     * @ibatorgenerated Thu Dec 24 08:51:47 ICT 2015
     */
    int updateByPrimaryKeySelective(NocSCMangLuoi record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table NOC_SU_CO_MANG_LUOI
     *
     * @ibatorgenerated Thu Dec 24 08:51:47 ICT 2015
     */
    int updateByPrimaryKey(NocSCMangLuoi record);
    
    
    List<SYS_PARAMETER> getCaTrucList();

	List<SYS_PARAMETER> getSCList();

	List<NocSCMangLuoi> getNocSCMangLuoiFilter(String startDate, String endDate, String shift, String deptCode,String username,
			String loaisc,String statusProcess,String faultID, Integer startRecord, Integer endRecord, String sortfield, String sortorder, String strWhere);
	
	int countNocSCMangLuoiFilter(String startDate, String endDate, String shift, String deptCode,String username,String loaisc,String statusProcess,String faultID,
			String strWhere);

	
	List<NocSCMangLuoi> getBCSCFilter(String startdate,String enddate,
									  String startweek,String endweek,
									  String startmonth,String endmonth,
									  String startquarter,String endquarter,
									  String syear,String eyear,
									  String type,String region,
									  Integer startRecord, Integer endRecord, String sortfield, String sortorder, String strWhere);
	
	int countBCSCFilter(String startdate,String enddate,
						String startweek,String endweek,
						String startmonth,String endmonth,
						String startquarter,String endquarter,
						String syear,String eyear,
						String type, String region,String strWhere);
	
	
	
	List<NocSCMangLuoi> checkCalendarPrimaryKey(String maPhong, String tenSuCo, String loaisc, String tgBatDau,
			int caTruc, String id);

	// VanAnh.25/04/2016: Lay thong tin su co mang luoi tren Dashboard
	List<NocSCMangLuoi> getDBSuCoMangLuoi(String region, String maPhong,
			String catruc,String ngayTruc,
			Integer shiftID,String note);
	
	List<NocSCMangLuoi> getNocSCMangLuoiFilterShift(String startDate, String endDate,String region,String shift, String deptCode,String username,String loaisc,String type );

	int insertTrouble(NocSCMangLuoi trouble);
	
	// TNV Lay du lieu hien thi dashboard mat lien lac & su co
	//ds su co
	List<NocSCMangLuoi> getSucoListForDashboard(String date,String deptCode,Integer startRecord, Integer endRecord, String sortfield, String sortorder, String strWhere);
	int countSucoListForDashboard(String date,String deptCode,Integer startRecord, Integer endRecord, String sortfield, String sortorder, String strWhere);
	//ds mll
	List<NocBaocaoMatlienlac> getMllListForDashboard(String date,String deptCode,Integer startRecord, Integer endRecord, String sortfield, String sortorder, String strWhere);
	int countMllListForDashboard(String date,String deptCode,Integer startRecord, Integer endRecord, String sortfield, String sortorder, String strWhere);
	
	// 13/01/2017 TVN ds canh bao
	//<!-- danh sach canh bao mat lien lac Thanhnv -->
	List<QuanlyMatlienlac> getCanhbaoMllList(String sdateF, String sdateT, String edateF, String edateT, String bscid,
			String cellid, String vendor, String district, String alarmName, String province, String group, String team,
			String alarmType, String netWork, String region, String severityF, String username,String causeby, 
			boolean isDownSite, Integer startRecord,
			Integer endRecord, String sortfield, String sortorder, String strWhere);
	
	//<!-- count canh bao mat lien lac Thanhnv -->
	Integer countCanhbaoMllList(String sdateF, String sdateT, String edateF, String edateT, String bscid,
			String cellid, String vendor, String district, String alarmName, String province, String group, String team,
			String alarmType, String netWork, String region, String severityF, String username,String causeby, 
			boolean isDownSite, Integer startRecord,
			Integer endRecord, String sortfield, String sortorder, String strWhere);
	
	//<!-- 	TNV 19/01/2017 bao cao, thong ke, dashboard module su co -->

	// <!-- danh sach su co cho dashboard suco -->
	List<NocSCMangLuoi> getBaocaoSuco(String tt, String donvi, String loaiThietbi, String tenThietbi, String donvi2,
			String province, String district, String daiVt, String team, String date, String week, String month,
			String quater, String year, String type, String deptCode, Integer startRecord, Integer endRecord, String sortfield,
			String sortorder, String strWhere);

	// <!-- dem su co cho dashboard suco -->
	Integer countBaocaoSuco(String tt, String donvi, String loaiThietbi, String tenThietbi, String donvi2,
			String province, String district, String daiVt, String team, String date, String week, String month,
			String quater, String year, String type, String deptCode, Integer startRecord, Integer endRecord, String sortfield,
			String sortorder, String strWhere);

	// <!-- danh sach bao cao mat lien lac cho dashboard su co -->

	List<NocBaocaoMatlienlac> getBaocaoMll(String tt, String donvi, String loaiThietbi, String tenThietbi, String donvi2,
			String province, String district, String daiVt, String team, String date, String week, String month,
			String quater, String year, String type, String deptCode, Integer startRecord, Integer endRecord, String sortfield,
			String sortorder, String strWhere);

	// <!-- dem bao cao mat lien lac cho dashboard su co -->
	Integer countBaocaoMll(String tt, String donvi, String loaiThietbi, String tenThietbi, String donvi2,
			String province, String district, String daiVt, String team, String date, String week, String month,
			String quater, String year, String type, String deptCode, Integer startRecord, Integer endRecord, String sortfield,
			String sortorder, String strWhere);
	
	// <!-- danh sach bao cao so luong su co cho dashboard su co -->

		List<DanhGiaSLASCAndMLL> getBaocaoSLASuco(String tt, String donvi, String loaiThietbi, String tenThietbi, String donvi2,
				String province, String district, String daiVt, String team, String date, String week, String month,
				String quater, String year, String type, String deptCode, Integer startRecord, Integer endRecord, String sortfield,
				String sortorder, String strWhere);

		// <!-- dem bao cao so luong su co cho dashboard su co -->
		Integer countBaocaoSLASuco(String tt, String donvi, String loaiThietbi, String tenThietbi, String donvi2,
				String province, String district, String daiVt, String team, String date, String week, String month,
				String quater, String year, String type, String deptCode, Integer startRecord, Integer endRecord, String sortfield,
				String sortorder, String strWhere);
	//<!--   get chart su co 7 day -->
	List<AlarmSLADailyReport7Day> getChartSuco7Day(String type,String startDate);

	/*Thống kê số lượng các trạm MLL*/
	List<NocSCMangLuoi> getDBThongKeMLL(String region, String maPhong,
			String catruc, String ngayTruc, Integer shiftID, String note);

	// lay thong tin su co cho thong tin ca truc
	List<NocSCMangLuoi> getShiftSuCoMangLuoi(String shiftid, String ngayTKTo,
			String ngayTK, String type, String region, String maPhong,String username);

	List<NocDanhGiaCSHT> getShiftSLAXuLySuCo(String shiftid, String ngayTKTo,
			String ngayTK, String type, String region, String maPhong,String username);

	List<NocDanhGiaCSHT> getShiftThongKeMLL(String shiftid, String ngayTKTo,
			String ngayTK, String type, String region, String maPhong,String username);

	int sendSMSToBO(String idList, String username);
	
	// lay thong tin chi tiet su co hien thi chuc nang dashboard home. AnhCTV.08/11/2017
	List<NocSCMangLuoi> getDBHomeSuCoDetail(String ngayTruc, String username);
	
	
}