package dao.bts;

import java.util.List;

import vo.bts.CountAlarmLog;
import vo.bts.RalarmRogActiveCisco;

public interface RalarmRogActiveCiscoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_ALARM_LOG_ACTIVE_CISCO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    void insert(RalarmRogActiveCisco record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_ALARM_LOG_ACTIVE_CISCO
     *
     * @ibatorgenerated Wed Oct 10 17:04:59 ICT 2018
     */
    void insertSelective(RalarmRogActiveCisco record);
    
    
    List<RalarmRogActiveCisco>  ralarmList (
    		String netWork,		String severity,	String region,	String neType,
    		String sdateF, 		String sdateT,		String edateF, 	String edateT, 
    		String province, 	String district , 	String bscid ,	String team,
			String alarmType,	String vendor, 		String cellid, 	String duaration
			);
	List<CountAlarmLog> getCountForSeverity(String sdateF, String sdateT,
			String edateF, String edateT, String bscid, String cellid,
			String vendor, String district, String alarmName, String function,
			String netWork, String username, String province, String team,
			String alarmType, String alarmMappingName, String statusView,
			String duaration,String region,String unAlarmMappingName,String severity, String neType,
			String center);
	
    
}