package dao.bts;

import java.util.List;

import vo.bts.CountAlarmLog;
import vo.bts.RAlarmLog;
import vo.bts.SYS_PARAMETER;


public interface RAlarmLogDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_ALARM_LOG
     *
     * @ibatorgenerated Mon Dec 09 08:30:21 ICT 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_ALARM_LOG
     *
     * @ibatorgenerated Mon Dec 09 08:30:21 ICT 2013
     */
    void insert(RAlarmLog record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_ALARM_LOG
     *
     * @ibatorgenerated Mon Dec 09 08:30:21 ICT 2013
     */
    void insertSelective(RAlarmLog record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_ALARM_LOG
     *
     * @ibatorgenerated Mon Dec 09 08:30:21 ICT 2013
     */
    RAlarmLog selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_ALARM_LOG
     *
     * @ibatorgenerated Mon Dec 09 08:30:21 ICT 2013
     */
    int updateByPrimaryKeySelective(RAlarmLog record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table R_ALARM_LOG
     *
     * @ibatorgenerated Mon Dec 09 08:30:21 ICT 2013
     */
    int updateByPrimaryKey(RAlarmLog record);
    
    List<RAlarmLog> getAlarmLogAtShift(String netWork, String day, String alarmType,
			String status, String bsc, String cell);
//
//	List<RAlarmLog> getAlarmLogSameAtShift(String netWork, String operator,
//			String system, String alarmType, String sdate, String edate);

	int updateShiftID(String netWork, String id, String shiftId);

	List<SYS_PARAMETER> titleForm(String function, String network, String  typeForm);

	int deleteAlarmLog(int id, String function);

	RAlarmLog selectByPrimaryKey(int id, String function);

	int insert(RAlarmLog alarmLog, String function);

	int update(RAlarmLog alarmLog, String function);

	int ackAlarmLog(Integer id, Integer shiftID, String function,String userName,String statusEndTime,String etime);

	/*List<CountAlarmLog> getCountForSeverity(String sdate, String edate,
			String bscid, String cellid, String vendor, String district,
			String alarmName, String function, String type, String username,
			String province, String team, String alarmType,
			String alarmMappingName);

	int countRAlarmLog(String sdate, String edate, String bscid, String cellid,
			String vendor, String district, String alarmName, String function,
			String severity, String netWork, String username, String province,
			String team, String alarmType, String alarmMappingName,
			String statusFinish, String strWhere);

	List<RAlarmLog> getRAlarmLog(String sdate, String edate, String bscid,
			String cellid, String vendor, String district, String alarmName,
			String function, String severity, String strWhere, Integer startRecord,
			Integer endRecord, String sortfield, String sortorder, String netWork,
			String username, String province, String team, String alarmType,
			String alarmMappingName, String statusFinish);*/

	int unAckAlarmLog(Integer parseInt, String function,String userName,String statusEndTime);


	List<RAlarmLog> getRAlarmLogInfoFilter(String siteid);
	//Dem so alarm thong ke trong cham diem ca nhan. status: trang thai xu ly.
	int countAlarmDetailAssess(String dateF, String dateT, String catruc,
			String users, String status,String network,
			String neType, String severity,String columnheader, String strWhere);

	//Lay danh sach alarm thong ke trong cham diem ca nhan. status: trang thai xu ly.
	List<RAlarmLog> getAlarmDetailAssess(String dateF, String dateT,
			String catruc, String users, String status,String network,
			String neType, String severity,String columnheader, String strWhere,
			Integer startRecord, Integer endRecord, String sortfield, String sortorder);

	//lay danh sach canh bao moi xuat hien can canh bao am thanh
	List<RAlarmLog> getAlarmAlert(String sdateF, String sdateT, String edateF,
			String edateT, String bscid, String cellid, String vendor,
			String district, String alarmName, String function,
			String severity, String netWork, String username, String province,
			String team, String alarmType, String alarmMappingName,
			String statusFinish, String statusView, 
			String region, String unAlarmMappingName);
	//dem so canh bao moi xuat hien
	List<Integer> getIdAlarmAlert(String sdateF, String sdateT, String edateF,
			String edateT, String bscid, String cellid, String vendor,
			String district, String alarmName, String function,
			String severity, String netWork, String username, String province,
			String team, String alarmType, String alarmMappingName,
			String statusFinish, String statusView, 
			String region, String unAlarmMappingName);

	int updateStatusAlerted(String idList, String type);
	
	// Lay du lieu cho form xu ly canh bao  (diary --> quan ly canh bao)
	List<RAlarmLog> getDataAlarm(String center, String sdateF, String sdateT,  String bscid, String cellid, String vendor, String district, String alarmName, String province, 
			String team, String alarmType, String netWork, String region, String severityF);
	
	RAlarmLog getCanhBaoById(Integer id);

	int updateXLCanhBao(RAlarmLog xuLyCB);
	void insertToAlarmHandling(RAlarmLog alarm);

	List<RAlarmLog> getQLCBDashBoardData(Integer catruc, String dept);
	
	// ANHCTV: Tach lenh tim kiem theo tung loai RAN, CORE, Truyen Dan. ANHCTV
	List<CountAlarmLog> getCountForSeverity(String sdateF, String sdateT,
			String edateF, String edateT, String bscid, String cellid,
			String vendor, String district, String alarmName, String function,
			String netWork, String username, String province, String team,
			String alarmType, String alarmMappingName, String statusView,
			String duaration,String region,String unAlarmMappingName,String severity, String neType,
			String center);
	
	int countRAlarmLog(String sdateF, String sdateT, String edateF,
			String edateT, String bscid, String cellid, String vendor,
			String district, String alarmName, String function,
			String severity, String netWork, String username, String province,
			String team, String alarmType, String alarmMappingName,
			String statusFinish, String strWhere, String statusView,
			String duaration,String region,String unAlarmMappingName, String neType, 
			String center);
	
	List<RAlarmLog> getRAlarmLog(String sdateF, String sdateT, String edateF,
			String edateT, String bscid, String cellid, String vendor,
			String district, String alarmName, String function,
			String severity, String strWhere, Integer startRecord, Integer endRecord,
			String sortfield, String sortorder, String netWork,
			String username, String province, String team, String alarmType,
			String alarmMappingName, String statusFinish, String statusView,
			String duaration,String region,String unAlarmMappingName, String neType, 
			String center);
	
	// TRUNG NQ 5/1/2017 gui canh bao cho BO xu ly dong thoi cap nhat trang thai
	int sendAlarmToBO(String idList, String username, String tgChuyen);

	List<String> getNeByNetwork(String network);
	
	// ThanhNv 16/01/2016 cap nhat nguyen nhan, noi dung xu ly canh bao mat lien lac
	void updateReasonAndHanding(RAlarmLog alarm);
	
	// TRUNGNQ 4/7/2018 update acknowledge va nguyen nhan mll uctt cho bao cao mll - ran
	void updateCbMll(String id, String acknowledge, String nguyenNhanMll, String partitionName, String nguoiSua);
}