package dao.bts;

import java.util.List;

import vo.bts.SYS_PARAMETER;
import vo.bts.SmsContents;

public interface SmsContentsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SMS_CONTENTS
     *
     * @ibatorgenerated Thu Oct 03 09:22:41 ICT 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SMS_CONTENTS
     *
     * @ibatorgenerated Thu Oct 03 09:22:41 ICT 2013
     */
    void insert(SmsContents record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SMS_CONTENTS
     *
     * @ibatorgenerated Thu Oct 03 09:22:41 ICT 2013
     */
    void insertSelective(SmsContents record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SMS_CONTENTS
     *
     * @ibatorgenerated Thu Oct 03 09:22:41 ICT 2013
     */
    SmsContents selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SMS_CONTENTS
     *
     * @ibatorgenerated Thu Oct 03 09:22:41 ICT 2013
     */
    int updateByPrimaryKeySelective(SmsContents record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SMS_CONTENTS
     *
     * @ibatorgenerated Thu Oct 03 09:22:41 ICT 2013
     */
    int updateByPrimaryKey(SmsContents record);

	int sendMail(SmsContents record);
	
	int sendSms(SmsContents record);
	int sendSmsDDh(SmsContents record);
	// lay danh sach tieu de chuc nang 
	List<SYS_PARAMETER> titleForm(String function, String typeForm);
	// lay danh sach sms total
	List<SmsContents> getSMSContentTotal(String sdate, String edate);
	// lay danh sach sms detail
	List<SmsContents> getSMSContentDetail(String sdate, String edate,
			String username, String isdn, String alarmType);

	int checkIsdn(String isdn);
	// gui sms den quan ly cua nguoi sua.
	int sendSMSForManagerOfUser(String content, String username,String type);

	void insertSmsChan(SmsContents record);

	/*int sendSMS(SmsContents record);*/
}