package dao.bts;

import java.util.List;

import vo.bts.SYS_PARAMETER;

public interface SYS_PARAMETERDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    void insert(SYS_PARAMETER record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    void insertSelective(SYS_PARAMETER record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    SYS_PARAMETER selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    int updateByPrimaryKeySelective(SYS_PARAMETER record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_PARAMETER
     *
     * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
     */
    int updateByPrimaryKey(SYS_PARAMETER record);

	List<SYS_PARAMETER> getSysParameterByCode(String code);

	List<SYS_PARAMETER> getSystemNotInSysMenu();

	List<SYS_PARAMETER> checkWarningTypeExits(String code, String name);

	List<SYS_PARAMETER> getListTTPACount();

	SYS_PARAMETER getSPByValue(String value);
	
	List<SYS_PARAMETER> getSPByCodeAndName(String code, String name);

	SYS_PARAMETER getValueByCodeName(String pName, String pValue);

	int updateByCodeName(SYS_PARAMETER record);

	List<SYS_PARAMETER> getSysParametersFilter(String code, String name,
			String column, String order);

	List<SYS_PARAMETER> distinctMaThamSo();

	List<SYS_PARAMETER> titleSysParameter();

	List<SYS_PARAMETER> getListHourOnDay();

	List<SYS_PARAMETER> getAlarmType();

	List<SYS_PARAMETER> getStatusFinish();

	List<SYS_PARAMETER> getCausebySystem();

	List<SYS_PARAMETER> getStatusDVTUCTT();

	List<SYS_PARAMETER> getStatusNode();
	
	List<SYS_PARAMETER> getCondition();

	SYS_PARAMETER getTimerLossDip();
	
	// @author Thangpx
	/*List<SYS_PARAMETER> getSPByName(String pName, String pValue);
*/
	List<SYS_PARAMETER> getSPByName(String alarmType, String netWork,
			String typeForm);

	List<SYS_PARAMETER> getVendorList();

	List<SYS_PARAMETER> getGroupQualityList();

	List<SYS_PARAMETER> getProcessFeedbackJob();

	List<SYS_PARAMETER> getStatusOfCentralFb();

	List<SYS_PARAMETER> getIsEnableCableOdfList();

	List<SYS_PARAMETER> getLoaiBaoCaoList();

	List<SYS_PARAMETER> getColorOdfLienTang();

	List<SYS_PARAMETER> getAsImportWarehouseUnit();

	List<SYS_PARAMETER> asImportWarehouseByUnit(String unit);

	List<SYS_PARAMETER> getSameUnitAssets();

	List<SYS_PARAMETER> getListFbIbc();

	List<SYS_PARAMETER> getHomePage(String module); 
	
	List<SYS_PARAMETER> getUserAdmin();

	List<SYS_PARAMETER> titleSysParameterByCode(String typeCode, String string);

	List<SYS_PARAMETER> getModuleWhenLogin(String moduleValue);

	List<SYS_PARAMETER> getEquipmentType();

	List<SYS_PARAMETER> getStatusEquipmentType();

	List<SYS_PARAMETER> getStatusIsoLicenseSoft();

	List<SYS_PARAMETER> getSeverityList();

	List<SYS_PARAMETER> getStatusViewList();

	List<SYS_PARAMETER> getAckStatusList();

	List<SYS_PARAMETER> getVendorForResourceList();

	List<SYS_PARAMETER> getWarningType();

	List<SYS_PARAMETER> getPositionList();

	List<SYS_PARAMETER> getSysParaForBlacklist(String username,
			String alarmType, String alarmId, String alarmName);

	List<SYS_PARAMETER> getNetworkTypeList();

	List<SYS_PARAMETER> getNeTypeList();

	List<SYS_PARAMETER> getRawTableList();

	List<SYS_PARAMETER> getAlarmColumnNameList();

	List<SYS_PARAMETER> getYesNoList();

	List<SYS_PARAMETER> getSearchList();
	
	List<SYS_PARAMETER> getTypeEmailHourList();

	List<SYS_PARAMETER> getInputStatusList();
	
	List<SYS_PARAMETER> getMailLevel();

	List<SYS_PARAMETER> getShiftHeader(String region);

	List<SYS_PARAMETER> getNetworkForOnAir();

	List<SYS_PARAMETER> getFormsLogin();

	List<SYS_PARAMETER> getStatusSendMail();

	List<SYS_PARAMETER> getSmsOtherForSysUsers();

	List<SYS_PARAMETER> getStatusDyTrx();

	List<SYS_PARAMETER> getTypeDyTrx();

	List<SYS_PARAMETER> getTypeDyTrx3g();

	List<SYS_PARAMETER> getAlamNameList(String warningTp);

	List<SYS_PARAMETER> getBrandName();

	List<SYS_PARAMETER> getLLProvider();

	List<SYS_PARAMETER> getLeaseLine(String llNode, String llProvider);

	List<SYS_PARAMETER> getRegionList();
	
	List<SYS_PARAMETER> getDateList();
	
	
	//kiem tra khu vuc dang ky có ton tai ko
	boolean checkRegionExit(String regionRole);
	// lay các trạng thái UCTT
	List<SYS_PARAMETER> getStatusUCTT();
	// lay danh sach severity cho chuc nang chart
	List<SYS_PARAMETER> getSeverityListChart();
	// Lay danh sach nhiem vu
	List<SYS_PARAMETER> getDSNhiemVu();

	List<SYS_PARAMETER> getSysParaForBlacklistGroup(String groupCode,
			String alarmType, String alarmId, String alarmName);

	public List<String> getTypeProject(String code);
	
	//Danh sach he thong thiet bi trong ca truc
	List<SYS_PARAMETER> getDSHeThong();
	//Danh sach  muc do su co
	List<SYS_PARAMETER> getMucDoSCList();
	//Danh sach  nguyen nhan su co
	List<SYS_PARAMETER> getNguyenNhanSCList();
	// danh sach ca truc : sang trua toi
	List<SYS_PARAMETER> getCaTrucList();
	// danh sach to nhom phu trach trong form troubleshootingForm
	List<SYS_PARAMETER> getToNhomPhuTrachListList();
	// danh sach to nhom phu trach trong form troubleshootingForm
	List<SYS_PARAMETER> getTrangThaiTroubleShootList();
	
//	<!-- 	Bao cao SLA -->
//	<!-- 1 thanhnv 2016/01/02 new Danh sach trung tam: NOC, TTML_MB, TTML_MT, TTML_MN -->
	List<SYS_PARAMETER> getTrungtamSlaList();
//	<!-- 2 thanhnv 2016/01/02 new Danh sach don vi: NOC_MB, NOC_MT, NOC_MN -->
		List<SYS_PARAMETER> getDonviSlaList();
//	<!-- 3 thanhnv 2016/01/02 new Danh sach LOAI TB: PS_CORE, CS_CORE -->
		List<SYS_PARAMETER> getLoaiTbSlaList();
//	<!-- 4 thanhnv 2016/01/02 new Danh sach don vi2 : TINH, DAI -->
		List<SYS_PARAMETER> getDonvi2SlaList();
	// lay danh sach trang thai xu ly su co/mll/cong viec. ANHCTV 09/01/2017
		List<SYS_PARAMETER> getSLAProcess();
	
	// TRUNG NQ LAY DANH SACH LOAI THIET BI CORE_CS, CORE_PS, ...
	List<String> getNetworkByCenter(String center);

	
	// lay danh sach muc do anh huong.ANHCTV 06/02/2017
	List<SYS_PARAMETER> getMucDoAnhHuong();

	List<SYS_PARAMETER> getStatusProcessSuCo();
	List<SYS_PARAMETER> getTypeOfImportSPEED(String typeFile);
	
	List<SYS_PARAMETER> getTypeOfImportTsNenRan(String typeFile);
}