package dao.bts;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vo.bts.SYS_PARAMETER;

public class SYS_PARAMETERDAOImpl extends SqlMapClientDaoSupport implements SYS_PARAMETERDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SYS_PARAMETER
	 *
	 * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
	 */
	public SYS_PARAMETERDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SYS_PARAMETER
	 *
	 * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
	 */
	public int deleteByPrimaryKey(Integer id) {
		SYS_PARAMETER key = new SYS_PARAMETER();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("SYS_PARAMETER1.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SYS_PARAMETER
	 *
	 * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
	 */
	public void insert(SYS_PARAMETER record) {
		getSqlMapClientTemplate().insert("SYS_PARAMETER1.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SYS_PARAMETER
	 *
	 * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
	 */
	public void insertSelective(SYS_PARAMETER record) {
		getSqlMapClientTemplate().insert("SYS_PARAMETER1.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SYS_PARAMETER
	 *
	 * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
	 */
	public SYS_PARAMETER selectByPrimaryKey(Integer id) {
		SYS_PARAMETER key = new SYS_PARAMETER();
		key.setId(id);
		SYS_PARAMETER record = (SYS_PARAMETER) getSqlMapClientTemplate()
				.queryForObject("SYS_PARAMETER1.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SYS_PARAMETER
	 *
	 * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
	 */
	public int updateByPrimaryKeySelective(SYS_PARAMETER record) {
		int rows = getSqlMapClientTemplate().update("SYS_PARAMETER1.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SYS_PARAMETER
	 *
	 * @ibatorgenerated Thu Sep 06 10:56:36 ICT 2012
	 */
	public int updateByPrimaryKey(SYS_PARAMETER record) {
		int rows = getSqlMapClientTemplate().update("SYS_PARAMETER1.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSysParameterByCode(String code) {
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSysParameterByCode", code);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSystemNotInSysMenu() {

		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSystemNotInSysMenu", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> checkWarningTypeExits(String code, String name) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("name", name);
		parms.put("code", code);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.checkWarningTypeExits", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getListTTPACount() {

		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getListTTPACount", parms);
	}

	@Override
	public SYS_PARAMETER getSPByValue(String value) {

		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_VALUE", value);
		parms.put("P_DATA", null);
		SYS_PARAMETER record = (SYS_PARAMETER) getSqlMapClientTemplate().queryForObject("SYS_PARAMETER1.getSPByValue",
				parms);
		return record;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSPByCodeAndName(String code, String name) {

		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_CODE", code);
		parms.put("P_NAME", name);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSPByCodeAndName", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public SYS_PARAMETER getValueByCodeName(String pName, String pValue) {
		SYS_PARAMETER key = new SYS_PARAMETER();
		key.setCode(pName);
		key.setName(pValue);
		List<SYS_PARAMETER> record = getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getValueByCodeName", key);
		if (record != null)
			return record.get(0);
		else
			return null;
	}

	@Override
	public int updateByCodeName(SYS_PARAMETER record) {
		int rows = getSqlMapClientTemplate().update("SYS_PARAMETER1.updateByCodeName", record);
		return rows;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSysParametersFilter(String code, String name, String column, String order) {

		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_CODE", code);
		parms.put("P_NAME", name);
		parms.put("P_COLUMN", column);
		parms.put("P_ORDER", order);
		parms.put("P_DATA", null);

		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSysParametersFilter", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> distinctMaThamSo() {

		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);

		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.distinctMaThamSo", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> titleSysParameter() {

		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);

		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.titleSysParameter", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getListHourOnDay() {

		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);

		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getListHourOnDay", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getAlarmType() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getAlarmType", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusFinish() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusFinish", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getCausebySystem() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getCausebySystem", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusDVTUCTT() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);

		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusDVTUCTT", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusNode() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);

		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusNode", parms);
	}

	@Override
	public SYS_PARAMETER getTimerLossDip() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		SYS_PARAMETER record = (SYS_PARAMETER) getSqlMapClientTemplate().queryForObject("SYS_PARAMETER1.getTimerLossDip",
				parms);
		return record;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getCondition() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);

		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getCondition", parms);
	}
	// @author Thang

	/*
	 * @Override public List<SYS_PARAMETER> getSPByName(String name, String
	 * value){
	 * 
	 * Map<String, Object> parms = new HashMap<String, Object>();
	 * parms.put("P_NAME", name); parms.put("P_VALUE", value);
	 * parms.put("P_DATA", null); return
	 * getSqlMapClientTemplate().queryForList("SYS_PARAMETER.getSPByName",
	 * parms); }
	 */
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSPByName(String alarmType, String netWork, String typeForm) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_NAME", alarmType);
		parms.put("P_REMARK", netWork);
		parms.put("P_TYPE_FORM", typeForm);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSPByName", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getVendorList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getVendorList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getGroupQualityList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getGroupQualityList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getProcessFeedbackJob() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getProcessFeedbackJob", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusOfCentralFb() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusOfCentralFb", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getIsEnableCableOdfList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getIsEnableCableOdfList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getLoaiBaoCaoList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getLoaiBaoCaoList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getColorOdfLienTang() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getColorOdfLienTang", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getAsImportWarehouseUnit() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getAsImportWarehouseUnit", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSameUnitAssets() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSameUnitAssets", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> asImportWarehouseByUnit(String unit) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_UNIT", unit);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.asImportWarehouseByUnit", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getListFbIbc() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getListFbIbc", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getHomePage(String module) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MODULE", module);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getHomePage", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getUserAdmin() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getUserAdmin", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> titleSysParameterByCode(String typeCode, String typeForm) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_CODE", typeCode);
		map.put("P_TYPE_FORM", typeForm);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.titleSysParameterByCode", map);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getModuleWhenLogin(String moduleValue) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MODULE_VALUE", moduleValue);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getModuleWhenLogin", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getEquipmentType() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getEquipmentType", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusEquipmentType() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusEquipmentType", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusIsoLicenseSoft() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusIsoLicenseSoft", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSeverityList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSeverityList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusViewList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusViewList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getAckStatusList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getAckStatusList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getVendorForResourceList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getVendorForResourceList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getWarningType() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getWarningType", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getPositionList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getPositionList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSysParaForBlacklist(String username, String alarmType, String alarmId,
			String alarmName) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
		parms.put("S_ALARM_TYPE", alarmType);
		parms.put("S_ALARM_ID", alarmId);
		parms.put("S_ALARM_NAME", alarmName);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSysParaForBlacklist", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getNetworkTypeList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getNetworkTypeList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getNeTypeList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getNeTypeList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getRawTableList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getRawTableList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getAlarmColumnNameList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getAlarmColumnNameList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getYesNoList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getYesNoList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSearchList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSearchList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getTypeEmailHourList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getTypeEmailHourList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getInputStatusList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getInputStatusList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getMailLevel() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getMailLevel", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getShiftHeader(String region) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_REGION", region);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getShiftHeader", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getNetworkForOnAir() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getNetworkForOnAir", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getFormsLogin() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getFormsLogin", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusSendMail() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusSendMail", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSmsOtherForSysUsers() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSmsOtherForSysUsers", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusDyTrx() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusDyTrx", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getTypeDyTrx() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getTypeDyTrx", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getTypeDyTrx3g() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getTypeDyTrx3g", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getAlamNameList(String warningTp) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_WARNING_TYPE", warningTp);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getAlamNameList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getBrandName() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getBrandName", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getLLProvider() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getLLProvider", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getLeaseLine(String llNode, String llProvider) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_LL_NODE", llNode);
		parms.put("P_LL_PROVIDER", llProvider);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getLeaseLine", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getRegionList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getRegionList", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getDateList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getDateList", parms);
	}

	@Override
	public boolean checkRegionExit(String regionRole) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_REGION_LIST", regionRole);
		parms.put("P_DATA", null);

		getSqlMapClientTemplate().queryForObject("SYS_PARAMETER1.checkRegionExit", parms);
		Integer record = (Integer) parms.get("P_DATA");

		return record >= 1 ? true : false;
	}

	// trang thai UCTT
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusUCTT() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusUCTT", parms);
	}

	// lay danh sach severity cho chuc nang chart
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSeverityListChart() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSeverityListChart", parms);
	}

	// lay danh sach nhiem vu trong ca truc
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getDSNhiemVu() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getDSNhiemVu", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSysParaForBlacklistGroup(String groupCode, String alarmType, String alarmId,
			String alarmName) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_GROUP_CODE", groupCode);
		parms.put("S_ALARM_TYPE", alarmType);
		parms.put("S_ALARM_ID", alarmId);
		parms.put("S_ALARM_NAME", alarmName);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSysParaForBlacklistGroup", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getTypeProject(String code) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_CODE", code);
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getTypeProject", parms);
	}

	// Danh sach he thong thiet bi trong ca truc
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getDSHeThong() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getDSHeThong", parms);
	}

	// thanhnv 2016/08/19 add new ds muc do su co
	@SuppressWarnings("unchecked")
	public List<SYS_PARAMETER> getMucDoSCList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getMucDoSCList", parms);
	}

	// thanhnv 2016/08/19 add new ds muc do su co
	@SuppressWarnings("unchecked")
	public List<SYS_PARAMETER> getNguyenNhanSCList() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getNguyenNhanSCList", parms);
	}
	
    @SuppressWarnings("unchecked")
   	@Override
   	public List<SYS_PARAMETER> getCaTrucList() {
   		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getCaTrucList", parms);
   	}
   	
    @SuppressWarnings("unchecked")
   	@Override
   	public List<SYS_PARAMETER> getToNhomPhuTrachListList() {
   		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getToNhomPhuTrachListList", parms);
   	}
	
    @SuppressWarnings("unchecked")
   	@Override
   	public List<SYS_PARAMETER> getTrangThaiTroubleShootList() {
   		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getTrangThaiTroubleShootList", parms);
   	}
   	
//	<!-- 	Bao cao SLA -->
//	<!-- 1 thanhnv 2016/01/02 new Danh sach trung tam: NOC, TTML_MB, TTML_MT, TTML_MN -->
    @SuppressWarnings("unchecked")
   	@Override
   	public List<SYS_PARAMETER> getTrungtamSlaList() {
   		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getTrungtamSlaList", parms);
   	}
//	<!-- 2 thanhnv 2016/01/02 new Danh sach don vi: NOC_MB, NOC_MT, NOC_MN -->
    @SuppressWarnings("unchecked")
   	@Override
   	public 	List<SYS_PARAMETER> getDonviSlaList() {
   		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getDonviSlaList", parms);
   	}
//	<!-- 3 thanhnv 2016/01/02 new Danh sach LOAI TB: PS_CORE, CS_CORE -->
    @SuppressWarnings("unchecked")
   	@Override
   	public 	List<SYS_PARAMETER> getLoaiTbSlaList() {
   		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getLoaiTbSlaList", parms);
   	}
//	<!-- 4 thanhnv 2016/01/02 new Danh sach don vi2 : TINH, DAI -->
    @SuppressWarnings("unchecked")
   	@Override
   	public 	List<SYS_PARAMETER> getDonvi2SlaList() {
   		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getDonvi2SlaList", parms);
   	}

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getNetworkByCenter(String center) {
		// TODO Auto-generated method stub
		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("p_center", center);
   		parms.put("p_data", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getNetworkByCenter", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getSLAProcess() {
		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getSLAProcess", parms);
   	
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getMucDoAnhHuong() {
		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getMucDoAnhHuong", parms);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getStatusProcessSuCo() {
		Map<String, Object> parms = new HashMap<String, Object>();
   		parms.put("P_DATA", null);
       	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getStatusProcessSuCo", parms);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getTypeOfImportSPEED(String typeFile) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_NAME", typeFile);
    	parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getTypeOfImportSPEED", parms);
	}
	@SuppressWarnings("unchecked")
	@Override
	public List<SYS_PARAMETER> getTypeOfImportTsNenRan(String typeFile) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_NAME", typeFile);
    	parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_PARAMETER1.getTypeOfImportTsNenRan", parms);
	}
}