package dao.bts;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import vo.bts.SYS_PARAMETER;
import vo.bts.SysUsers;

public class SysUsersDAOImpl extends SqlMapClientDaoSupport implements SysUsersDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USERS
     *
     * @ibatorgenerated Wed Oct 24 16:22:23 ICT 2012
     */
    public SysUsersDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USERS
     *
     * @ibatorgenerated Wed Oct 24 16:22:23 ICT 2012
     */
    public int deleteByPrimaryKey(String id) {
        int rows = getSqlMapClientTemplate().delete("SYS_USERS1.ibatorgenerated_deleteByPrimaryKey", id);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USERS
     *
     * @ibatorgenerated Wed Oct 24 16:22:23 ICT 2012
     */
    public void insert(SysUsers record) {
        getSqlMapClientTemplate().insert("SYS_USERS1.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USERS
     *
     * @ibatorgenerated Wed Oct 24 16:22:23 ICT 2012
     */
    public void insertSelective(SysUsers record) {
        getSqlMapClientTemplate().insert("SYS_USERS1.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USERS
     *
     * @ibatorgenerated Wed Oct 24 16:22:23 ICT 2012
     */
    public SysUsers selectByPrimaryKey(String username) {
        SysUsers key = new SysUsers();
        key.setUsername(username);
        SysUsers record = (SysUsers) getSqlMapClientTemplate().queryForObject("SYS_USERS1.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }
    
    public SysUsers selectByID(String id) {
        SysUsers key = new SysUsers();
        key.setId(Integer.parseInt(id));
        SysUsers record = (SysUsers) getSqlMapClientTemplate().queryForObject("SYS_USERS1.selectByID", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USERS
     *
     * @ibatorgenerated Wed Oct 24 16:22:23 ICT 2012
     */
    public int updateByPrimaryKeySelective(SysUsers record) {
        int rows = getSqlMapClientTemplate().update("SYS_USERS1.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USERS
     *
     * @ibatorgenerated Wed Oct 24 16:22:23 ICT 2012
     */
    public int updateByPrimaryKey(SysUsers record) {
        int rows = getSqlMapClientTemplate().update("SYS_USERS1.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @SuppressWarnings("unchecked")
	public List<SysUsers> getUsersFilter(String maPhong, String username, String email, String phone, String isEnable, 
			String rolesAddUsers, String fullName, String column, String order){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MA_PHONG", maPhong);
		parms.put("P_USERNAME", username);
		parms.put("P_EMAIL", email);
		parms.put("P_PHONE", phone);
		parms.put("P_IS_ENABLE", isEnable);
		parms.put("P_ROLES_ADD_USERS", rolesAddUsers);
		parms.put("P_FULLNAME", fullName);
		parms.put("P_COLUMN", column);
		parms.put("P_ORDER", order);
		parms.put("P_DATA", null);
		
		List<SysUsers> record = (List<SysUsers>) getSqlMapClientTemplate().queryForList("SYS_USERS1.getUsersFilter", parms);
		
		return record;
	}
    
	
	@SuppressWarnings("unchecked")
	public List<SysUsers> selectSysUsers(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
		getSqlMapClientTemplate().queryForList("SYS_USERS1.selectSysUsers", parms);
		List<SysUsers> record = (List<SysUsers>) parms.get("P_DATA");
		
		return record;
	}
	
	public int updateIsEnable(SysUsers record) {
        int rows = getSqlMapClientTemplate().update("SYS_USERS1.updateIsEnable", record);
        return rows;
    }
	
	@SuppressWarnings("unchecked")
	public List<SysUsers> getUserByMaPhong(String maPhong){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MA_PHONG", maPhong);
		parms.put("P_DATA", null);
		
		getSqlMapClientTemplate().queryForList("SYS_USERS1.getUserByMaPhong", parms);
		List<SysUsers> record = (List<SysUsers>)parms.get("P_DATA");
		
		return record;
	}
	
	@SuppressWarnings("unchecked")
	public List<SysUsers> getUsersByMaPhongDontId(String maPhong, Integer id){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MA_PHONG", maPhong);
		parms.put("P_ID", id);
		parms.put("P_DATA", null);
		
		getSqlMapClientTemplate().queryForList("SYS_USERS1.getUsersByMaPhongDontId", parms);
		List<SysUsers> record = (List<SysUsers>) parms.get("P_DATA");
		
		return record;
	}
	
	public int selectByUsernamePassword(String username, String password){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
		parms.put("P_PASSWORD", password);
		parms.put("P_DATA", null);
		getSqlMapClientTemplate().queryForObject("SYS_USERS1.selectByUsernamePassword", parms);
		Integer record = (Integer) parms.get("P_DATA");
		
		return record;
	}
	
	public int updatePasswordForUsername(String username, String password) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
		parms.put("P_PASSWORD", password);
        int rows = getSqlMapClientTemplate().update("SYS_USERS1.updatePasswordForUsername", parms);
        return rows;
    }
	
	@SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> selectAllSysUsers(){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
		List<SysUsers> record = getSqlMapClientTemplate().queryForList("SYS_USERS1.selectAllSysUsers", parms);
		
		return record;
	}
	
	@Override
	public SysUsers selectSysUsersByUsername(String username){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
		parms.put("P_DATA", null);
		SysUsers record = (SysUsers) getSqlMapClientTemplate().queryForObject("SYS_USERS1.selectSysUsersByUsername", parms);
		return record;
		
	}

	@Override
	public SysUsers selectSysUsersByfullName(String user) {
		SysUsers key = new SysUsers();
		key.setFullname(user);
		 SysUsers record = (SysUsers) getSqlMapClientTemplate().queryForObject("SYS_USERS1.selectSysUsersByfullName", key);
	        return record;
	}
	
	@SuppressWarnings("unchecked")
	@Override
    public List<SYS_PARAMETER> titleSysUsers(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.titleSysUsers", parms);
    }
    
    @SuppressWarnings("unchecked")
	@Override
    public List<SYS_PARAMETER> getQuyenTaoNDList(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.getQuyenTaoNDList", parms);
    }
    
    @SuppressWarnings("unchecked")
	@Override
    public List<SYS_PARAMETER> getTrangThaiList(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.getTrangThaiList", parms);
    }
    
    @SuppressWarnings("unchecked")
	@Override
    public List<SYS_PARAMETER> titleDoiMatKhau(){
    	
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.titleDoiMatKhau", parms);
    }
    
    @SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> selectUsersOfAlarm() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
		
		List<SysUsers> record = getSqlMapClientTemplate().queryForList("SYS_USERS1.selectUsersOfAlarm", parms);
		
		return record;
	}

    @SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> checkUser(String userN) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", userN);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.checkUser", parms);
	}
    
    @SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> getUserByUsername(String username) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.getUserByUsername", parms);
	}
    
    @Override
    public boolean getCountUserOfModule(String username, String system){
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
		parms.put("P_SYSTEM", system);
		parms.put("P_DATA", null);
		
		getSqlMapClientTemplate().queryForObject("SYS_USERS1.getCountUserOfModule", parms);
		Integer record = (Integer) parms.get("P_DATA");
		
		return record>=1?true:false;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> getUserByGroupSMS(String group) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_GROUP_SMS", group);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.getUserByGroupSMS", parms);
	}
    
	/*@Override
    public int updateRolesForUsername(String username, String receivingSms, String receivingEmail, String rolesAddUsers, String modifiedBy) {
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
		parms.put("P_RECEIVING_SMS", receivingSms);
		parms.put("P_RECEIVING_EMAIL", receivingEmail);
		parms.put("P_ROLES_ADD_USERS", rolesAddUsers);
		parms.put("P_MODIFIED_BY", modifiedBy);
    	
        getSqlMapClientTemplate().queryForObject("SYS_USERS1.updateRolesForUsername", parms);
        return 1;
    }*/
	@Override
	public int updateRolesForUsername(SysUsers record) {
        int rows = getSqlMapClientTemplate().update("SYS_USERS1.updateRolesForUsername", record);
        return rows;
    }
	
	@Override
    public int updateSysUserArea(String id, String isEnable, String alarmKpi) {
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_ID", id);
		parms.put("P_IS_ENABLE", isEnable);
		parms.put("P_ALARM_KPI", alarmKpi);
    	
        getSqlMapClientTemplate().queryForObject("SYS_USERS1.updateSysUserArea", parms);
        return 1;
    }
	
	@Override
    public int smsAddIsdn(String phone, String username) {
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_PHONE", phone);
		parms.put("P_USERNAME", username);
    	
        getSqlMapClientTemplate().queryForObject("SYS_USERS1.smsAddIsdn", parms);
        return 1;
    }
	
	@Override
    public int copyRoleToUsernameNew(String username, String createdBy, String usernameNew, String passwordNew, String emailNew) {
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
		parms.put("P_CREATED_BY", createdBy);
		parms.put("P_USERNAME_NEW", usernameNew);
		parms.put("P_PASSWORK_NEW", passwordNew);
		parms.put("P_EMAIL_NEW", emailNew);
        getSqlMapClientTemplate().queryForObject("SYS_USERS1.copyRoleToUsernameNew", parms);
        return 1;
    }
	
	@Override
    public int deleteRoleByUsername(String username) {
    	Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_USERNAME", username);
    	
        getSqlMapClientTemplate().queryForObject("SYS_USERS1.deleteRoleByUsername", parms);
        return 1;
    }
	
	@SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> getCheckSysUsersByEmail(String email, String id) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_EMAIL", email);
		parms.put("P_ID", id);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.getCheckSysUsersByEmail", parms);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getContactUser(String depCode) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DEPT", depCode);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.getContactUser", parms);
	}
	
	@SuppressWarnings("unchecked")
    @Override
	public List<SysUsers> checkEmailOfShift(String email) {
    	Map<String, Object> map = new HashMap<String, Object>();
    	map.put("P_EMAIL", email);
		map.put("P_DATA", null);
		
		return getSqlMapClientTemplate().queryForList("SYS_USERS1.checkEmailOfShift", map);
    }
	@SuppressWarnings("unchecked")
	@Override
	public SysUsers getUserByPhone(String phoneNumber) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_PHONE", phoneNumber);
		parms.put("P_DATA", null);
		List<SysUsers>  recordL =  getSqlMapClientTemplate().queryForList("SYS_USERS1.getUserByPhone", parms);
		SysUsers record = new SysUsers();
		if (recordL.size()>0)
		{
			record = recordL.get(0);
		}
		return record;
	}
/*
	@SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> getUserAllByMaPhong(String maPhong) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MA_PHONG", maPhong);
		parms.put("P_DATA", null);
		
		List<SysUsers> record = getSqlMapClientTemplate().queryForList("SYS_USERS1.getUserAllByMaPhong", parms);
		
		return record;
	}*/
	@SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> getUserAllByMaPhong(String dept, String team) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MA_PHONG", dept);
		parms.put("P_TEAM", team);
		parms.put("P_DATA", null);
		
		List<SysUsers> record = getSqlMapClientTemplate().queryForList("SYS_USERS1.getUserAllByMaPhong", parms);
		
		return record;
	}
	  @SuppressWarnings("unchecked")
		@Override
		public List<SysUsers> checkRole(String userN) {
			Map<String, Object> parms = new HashMap<String, Object>();
			parms.put("P_USERNAME", userN);
			parms.put("P_DATA", null);
	    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.checkRole", parms);
		}
	//lay user co chuc vu ngang bang hoac be hon nguoi giao viec
    @SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> getUserForWork(String deptCode, String diliver) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MA_PHONG", deptCode);
		parms.put("P_DILIVER", diliver);
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.getUserForWork", parms);
	}
    
  //lay thong tin Use kèm theo một số thông tin như khu vực use trực thuộc. AnhCTV:16/11/2015
  	 @SuppressWarnings("unchecked")
  	@Override
  	public SysUsers selectByUsename(String username) {
  		Map<String, Object> parms = new HashMap<String, Object>();
  		parms.put("P_USERNAME", username);
  		parms.put("P_DATA", null);
  		List<SysUsers>  recordL =  getSqlMapClientTemplate().queryForList("SYS_USERS1.selectByUsename", parms);
  		SysUsers record = new SysUsers();
  		if (recordL.size()>0)
  		{
  			record = recordL.get(0);
  		}
  		return record;
  	}
  	 
  // kiem tra quyen cua user dang nhap. neu quyen bang 0: user chi co quyen xem, >1: user co quyen chinh sua
  	 @Override
		public Integer checkRoleInShift (String userN, String region,String department) {
			Map<String, Object> parms = new HashMap<String, Object>();
			parms.put("P_USERNAME", userN);
			parms.put("P_REGION", region);
			parms.put("P_MA_PHONG", department);
			parms.put("P_DATA", null);
			getSqlMapClientTemplate().queryForObject("SYS_USERS1.checkRoleInShift", parms);
			Integer record = (Integer) parms.get("P_DATA");
       	return record;
			
		}

 	// lay danh sach user co quyen phe duyet cong viec. 12/04/2016
	@SuppressWarnings("unchecked")
	@Override
	public List<SysUsers> getUserApprove() {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_DATA", null);
    	return getSqlMapClientTemplate().queryForList("SYS_USERS1.getUserApprove", parms);
	}

	
	// lay chuoi email theo danh sach user. AnhCTV.03/03/2017
	@Override
	public String getMailList(String maPhong, String user) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("P_MA_PHONG", maPhong);
		parms.put("P_USERNAME", user);
		parms.put("P_DATA", null);
		getSqlMapClientTemplate().queryForObject("SYS_USERS1.getMailList", parms);
		String record = (String) parms.get("P_DATA");
		return record;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getMaPhongByUser(String user) {
		Map<String, Object> parms = new HashMap<String, Object>();
		parms.put("p_user", user);
		parms.put("p_data", null);
		return getSqlMapClientTemplate().queryForList("SYS_USERS1.getMaPhongByUser", parms);
		
	}

}