package dao.bts;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import vo.bts.SysUserArea;

public class SysUserAreaDAOImpl extends SqlMapClientDaoSupport implements SysUserAreaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USER_AREA
     *
     * @ibatorgenerated Fri Sep 06 00:40:35 ICT 2013
     */
    public SysUserAreaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USER_AREA
     *
     * @ibatorgenerated Fri Sep 06 00:40:35 ICT 2013
     */
    public void insert(SysUserArea record) {
        getSqlMapClientTemplate().insert("SYS_USER_AREA1.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_USER_AREA
     *
     * @ibatorgenerated Fri Sep 06 00:40:35 ICT 2013
     */
    public void insertSelective(SysUserArea record) {
        getSqlMapClientTemplate().insert("SYS_USER_AREA1.ibatorgenerated_insertSelective", record);
    }
   /* @SuppressWarnings("unchecked")
	@Override
	public List<String> getDistrictList(String province, String username) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_PROVINCE", province);
		map.put("P_USERNAME", username);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA.getDistrictList", map);
	}*/

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getProvinceList(String username) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_USERNAME", username);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA1.getProvinceList", map);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getTeamList(String province, String username) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_PROVINCE", province);
		map.put("P_USERNAME", username);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA1.getTeamList", map);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<String> getSubTeamList(String province, String username) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_PROVINCE", province);
		map.put("P_USERNAME", username);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA1.getSubTeamList", map);
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<SysUserArea> getUsersAreaByUsername(String username, String province, String district, String code,String region) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_USERNAME", username);
		map.put("S_PROVINCE", province);
		map.put("S_DISTRICT", district);
		map.put("S_CODE", code);
		map.put("P_REGION", region);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA1.getUsersAreaByUsername", map);
	}
	@SuppressWarnings("unchecked")
	@Override
	public List<SysUserArea> getAreaByUsername(String username) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_USERNAME", username); 
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA1.getAreaByUsername", map);
	}
	@Override
	public int insertAndUsersAreaByUser(String username, String checkedList) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_USERNAME", username);
		map.put("P_CHECKEDLIST", checkedList);
		getSqlMapClientTemplate().queryForObject("SYS_USER_AREA1.insertAndUsersAreaByUser", map);
		return 1;
	}
	
	@Override
	public int deleteSysUsersAreaByCheck(String checkedList) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_CHECKEDLIST", checkedList);
		getSqlMapClientTemplate().queryForObject("SYS_USER_AREA1.deleteSysUsersAreaByCheck", map);
		return 1;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getDistrictList(String province, String team,
			String username) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_PROVINCE", province);
		map.put("P_USERNAME", username);
		map.put("P_GROUPS", team);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA1.getDistrictList", map);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<String> getDeptListParent() {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA1.getDeptListParent", map);
	}
	/*22.01.2016.AnhCTV: phan quyen theo group*/
	@SuppressWarnings("unchecked")
	@Override
	public List<SysUserArea> getUsersAreaByGroupCode(String groupCode,
			String province, String district, String code, String region) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_GROUP_CODE", groupCode);
		map.put("S_PROVINCE", province);
		map.put("S_DISTRICT", district);
		map.put("S_CODE", code);
		map.put("P_REGION", region);
		map.put("P_DATA", null);
		return getSqlMapClientTemplate().queryForList("SYS_USER_AREA1.getUsersAreaByGroupCode", map);
	}

	@Override
	public int insertAndUsersAreaByGroup(String groupCode, String addCheckedList) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_GROUP_CODE", groupCode);
		map.put("P_CHECKEDLIST", addCheckedList);
		getSqlMapClientTemplate().queryForObject("SYS_USER_AREA1.insertAndUsersAreaByGroup", map);
		return 1;
	}

	@Override
	public int deleteGroupUsersAreaByCheck(String groupCode,
			String removeCheckedList) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("P_GROUP_CODE", groupCode);
		map.put("P_CHECKEDLIST", removeCheckedList);
		getSqlMapClientTemplate().queryForObject("SYS_USER_AREA1.deleteGroupUsersAreaByCheck", map);
		return 1;
	}

}